# Useful pandas functionality

Sample of different functions available for pandas

## Overview

Covers a range of different useful pandas functions for:

- importing a dataset from csv
- gaining overview information on the data set
- slicing and joining data frames
- masking to select rows in a data frame by specific column values
- grouping parts of the dataframe based on column values
- creating pivot tables to return descriptive statistics based on different columns

## Importing datasets and overview

In [1]:
import pandas as pd

df = pd.read_csv("G:\My Projects\housing data\kc_house_data.csv", index_col = 'id')

Shows the dimensions of the data frames, here we have 21613 rows (samples), with 20 collumns (features)

In [2]:
df.shape

(21613, 20)

Displays the first 5 entries into the dataframe

In [3]:
df.head(5)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [4]:
df[['bedrooms', 'price']].head(5)

            bedrooms     price
id
7129300520         3  221900.0
6414100192         3  538000.0
5631500400         2  180000.0
2487200875         4  604000.0
1954400510         3  510000.0

data types can be displayed

In [5]:
df.dtypes

date              object
price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

the describe function displays numerical information for specified columns in the dataframe

In [6]:
print(df['bedrooms'].describe())

count    21613.000000
mean         3.370842
std          0.930062
min          0.000000
25%          3.000000
50%          3.000000
75%          4.000000
max         33.000000
Name: bedrooms, dtype: float64

loc allows the selection of specific rows based on their index.

In [7]:


df.loc[[7129300520, 6414100192]]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639

specific rows can be selected by their implicit index (numerical 0 onwards)

In [8]:
df[0:10]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,3,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570

loc can also be used to slice specific rows and columns

In [9]:
df.loc[[7129300520, 6414100192], ['price', 'bedrooms', 'bathrooms']]

               price  bedrooms  bathrooms
id
7129300520  221900.0         3       1.00
6414100192  538000.0         3       2.25

## Masking

Pandas method of selecting rows based on specific column values

The below displays the rows that have a bedroom column value of 3

In [10]:
df[df.bedrooms==3]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,3,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
1736800520,20150403T000000,662500.0,3,2.50,3560,9796,1.0,0,0,3,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
114101516,20140528T000000,310000.0,3,1.00,1430,19901,1.5,0,0,4,7,1430,0,1927,0,98028,47.7558,-122.229,1780,12697
6054650070,20141007T000000,400000.0,3,1.75,1370,9680,1.0,0,0,4,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208
1875500060,20140731T000000,395000.0,3,2.00,1890,14040,2.0,0,0,3,7,1890,0,1994,0,98019,47.7277,-121.962,1890,14018
7983200060,20150424T000000,230000.0,3,1.00,1250,9774,1.0,0,0,4,7,1250,0,1969,0,98003,47.3343,-122.306,1280,8850
2524049179,20140826T000000,2000000.0,3,2.75,3050,44867,1.0,0,4,3,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
3814700200,20141120T000000,329000.0,3,2.25,2450,6500,2.0,0,0,4,8,2450,0,1985,0,98030,47.3739,-122.172,2200,6865
1202000200,20141103T000000,233000.0,3,2.00,1710,4697,1.5,0,0,5,6,1710,0,1941,0,98002,47.3048,-122.218,1030,4705
1794500383,20140626T000000,937000.0,3,1.75,2450,2691,2.0,0,0,3,8,1750,700,1915,0,98119,47.6386,-122.360,1760,3573
3303700376,20141201T000000,667000.0,3,1.00,1400,1581,1.5,0,0,5,8,1400,0,1909,0,98112,47.6221,-122.314,1860,3861
5101402488,20140624T000000,438000.0,3,1.75,1520,6380,1.0,0,0,3,7,790,730,1948,0,98115,47.6950,-122.304,1520,6235
8562750320,20141110T000000,580500.0,3,2.50,2320,3980,2.0,0,0,3,8,2320,0,2003,0,98027,47.5391,-122.070,2580,3980
7589200193,20141110T000000,535000.0,3,1.00,1090,3000,1.5,0,0,4,8,1090,0,1929,0,98117,47.6889,-122.375,1570,5080
9547205180,20140613T000000,696000.0,3,2.50,2300,3060,1.5,0,0,3,8,1510,790,1930,2002,98115,47.6827,-122.310,1590,3264
9270200160,20141028T000000,685000.0,3,1.00,1570,2280,2.0,0,0,3,7,1570,0,1922,0,98119,47.6413,-122.364,1580,2640
1432701230,20140729T000000,309000.0,3,1.00,1280,9656,1.0,0,0,4,6,920,360,1959,0,98058,47.4485,-122.175,1340,8808
8035350320,20140718T000000,488000.0,3,2.50,3160,13603,2.0,0,0,3,8,3160,0,2003,0,98019,47.7443,-121.977,3050,9232
8945200830,20150325T000000,210490.0,3,1.00,990,8528,1.0,0,0,3,6,990,0,1966,0,98023,47.3066,-122.371,1228,8840
9215400105,20150428T000000,450000.0,3,1.75,1250,5963,1.0,0,0,4,7,1250,0,1953,0,98115,47.6796,-122.301,970,5100
822039084,20150311T000000,1350000.0,3,2.50,2753,65005,1.0,1,2,5,9,2165,588,1953,0,98070,47.4041,-122.451,2680,72513
5245600105,20140916T000000,228000.0,3,1.00,1190,9199,1.0,0,0,3,7,1190,0,1955,0,98148,47.4258,-122.322,1190,9364
7518505990,20141231T000000,600000.0,3,1.75,1410,4080,1.0,0,0,4,7,1000,410,1950,0,98117,47.6808,-122.384,1410,4080
2799800710,20150407T000000,301000.0,3,2.50,2420,4750,2.0,0,0,3,8,2420,0,2003,0,98042,47.3663,-122.122,2690,4750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8562770720,20150423T000000,589999.0,3,2.50,2140,3628,2.0,0,0,3,8,1960,180,2006,0,98027,47.5370,-122.074,2280,2812
9211010300,20140707T000000,509900.0,3,2.50,3030,9053,2.0,0,0,3,8,3030,0,2009,0,98059,47.4945,-122.149,3010,6026
1220000371,20141231T000000,327500.0,3,2.50,1820,1866,2.0,0,0,3,8,1570,250,2008,0,98166,47.4643,-122.346,1660,6900
880000205,20140729T000000,249000.0,3,2.00,1260,1125,2.0,0,0,3,7,810,450,2011,0,98106,47.5262,-122.361,1260,1172
2522059251,20150409T000000,465000.0,3,2.50,2050,15035,2.0,0,0,3,9,2050,0,2006,0,98042,47.3619,-122.122,1300,15836
2855000110,20140808T000000,388000.0,3,2.50,2198,6222,2.0,0,2,3,8,2198,0,2010,0,98198,47.3906,-122.304,2198,7621
6821101731,20140930T000000,549000.0,3,2.25,1230,1380,3.0,0,0,3,8,1230,0,2013,0,98199,47.6521,-122.400,1760,5664
2770603523,20150422T000000,530000.0,3,2.50,1410,1250,2.0,0,0,3,8,1140,270,2010,0,98119,47.6515,-122.375,1720,2825
2255500123,20140820T000000,747450.0,3,2.50,2110,1339,2.0,0,0,3,8,1410,700,2014,0,98122,47.6088,-122.311,1630,2670
9521100031,20140618T000000,690000.0,3,3.25,1540,1428,3.0,0,0,3,9,1540,0,2013,0,98103,47.6648,-122.353,1660,3300
3438501862,20140513T000000,330000.0,3,2.50,1450,5008,1.0,0,0,3,7,840,610,2007,0,98106,47.5435,-122.357,2120,5019
6056111067,20140707T000000,230000.0,3,1.75,1140,1201,2.0,0,0,3,8,1140,0,2014,0,98108,47.5637,-122.295,1210,1552
1931300090,20140507T000000,610950.0,3,3.00,1680,1570,3.0,0,0,3,8,1680,0,2014,0,98103,47.6572,-122.346,1640,4800
9578500790,20141111T000000,399950.0,3,2.50,3087,5002,2.0,0,0,3,8,3087,0,2014,0,98023,47.2974,-122.349,2927,5183
7011201004,20140529T000000,645000.0,3,3.25,1730,1229,2.0,0,2,3,9,1320,410,2008,0,98119,47.6374,-122.369,1710,1686
7853420110,20141003T000000,594866.0,3,3.00,2780,6000,2.0,0,0,3,9,2780,0,2013,0,98065,47.5184,-121.886,2850,6000
7853420110,20150504T000000,625000.0,3,3.00,2780,6000,2.0,0,0,3,9,2780,0,2013,0,98065,47.5184,-121.886,2850,6000
3052700432,20141112T000000,490000.0,3,2.25,1500,1290,2.0,0,0,3,8,1220,280,2006,0,98117,47.6785,-122.375,1460,1375
952006823,20141202T000000,380000.0,3,2.50,1260,900,2.0,0,0,3,7,940,320,2007,0,98116,47.5621,-122.384,1310,1415
3832050760,20140828T000000,270000.0,3,2.50,1870,5000,2.0,0,0,3,7,1870,0,2009,0,98042,47.3339,-122.055,2170,5399
6632300207,20150305T000000,385000.0,3,2.50,1520,1488,3.0,0,0,3,8,1520,0,2006,0,98125,47.7337,-122.309,1520,1497
7570050450,20140910T000000,347500.0,3,2.50,2540,4760,2.0,0,0,3,8,2540,0,2010,0,98038,47.3452,-122.022,2540,4571
1931300412,20150416T000000,475000.0,3,2.25,1190,1200,3.0,0,0,3,8,1190,0,2008,0,98103,47.6542,-122.346,1180,1224
5100403806,20150407T000000,467000.0,3,2.50,1425,1179,3.0,0,0,3,8,1425,0,2008,0,98125,47.6963,-122.318,1285,1253
844000965,20140626T000000,224000.0,3,1.75,1500,11968,1.0,0,0,3,6,1500,0,2014,0,98010,47.3095,-122.002,1320,11303
7852140040,20140825T000000,507250.0,3,2.50,2270,5536,2.0,0,0,3,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
9834201367,20150126T000000,429000.0,3,2.00,1490,1126,3.0,0,0,3,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
2997800021,20150219T000000,475000.0,3,2.50,1310,1294,2.0,0,0,3,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287

this can also be extended into checking for multiple columns values

In [11]:
df[(df.bedrooms == 3) & (df.bathrooms == 1.0)]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.0,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
2414600126,20150415T000000,229500.0,3,1.0,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
114101516,20140528T000000,310000.0,3,1.0,1430,19901,1.5,0,0,4,7,1430,0,1927,0,98028,47.7558,-122.229,1780,12697
7983200060,20150424T000000,230000.0,3,1.0,1250,9774,1.0,0,0,4,7,1250,0,1969,0,98003,47.3343,-122.306,1280,8850
3303700376,20141201T000000,667000.0,3,1.0,1400,1581,1.5,0,0,5,8,1400,0,1909,0,98112,47.6221,-122.314,1860,3861
7589200193,20141110T000000,535000.0,3,1.0,1090,3000,1.5,0,0,4,8,1090,0,1929,0,98117,47.6889,-122.375,1570,5080
9270200160,20141028T000000,685000.0,3,1.0,1570,2280,2.0,0,0,3,7,1570,0,1922,0,98119,47.6413,-122.364,1580,2640
1432701230,20140729T000000,309000.0,3,1.0,1280,9656,1.0,0,0,4,6,920,360,1959,0,98058,47.4485,-122.175,1340,8808
8945200830,20150325T000000,210490.0,3,1.0,990,8528,1.0,0,0,3,6,990,0,1966,0,98023,47.3066,-122.371,1228,8840
5245600105,20140916T000000,228000.0,3,1.0,1190,9199,1.0,0,0,3,7,1190,0,1955,0,98148,47.4258,-122.322,1190,9364
1274500060,20140825T000000,204000.0,3,1.0,1000,12070,1.0,0,0,4,7,1000,0,1968,0,98042,47.3621,-122.110,1010,12635
2391600320,20150420T000000,480000.0,3,1.0,1040,5060,1.0,0,0,3,7,1040,0,1941,0,98116,47.5636,-122.394,890,5060
6300000287,20140609T000000,410000.0,3,1.0,1410,5060,1.0,0,0,4,7,910,500,1956,0,98133,47.7073,-122.340,1130,5693
1133000671,20140602T000000,315000.0,3,1.0,960,6634,1.0,0,0,3,6,960,0,1952,0,98125,47.7264,-122.310,1570,7203
4168000060,20150226T000000,153000.0,3,1.0,1200,10500,1.0,0,0,3,7,1200,0,1962,0,98023,47.3220,-122.351,1350,10500
6197800045,20140924T000000,290000.0,3,1.0,1210,33919,1.0,0,0,3,7,1210,0,1954,0,98058,47.4375,-122.184,1640,14910
546000875,20140523T000000,460000.0,3,1.0,1670,4005,1.5,0,0,4,7,1170,500,1939,0,98117,47.6878,-122.380,1240,4005
1432900240,20150508T000000,205000.0,3,1.0,1610,8579,1.0,0,0,4,7,1010,600,1962,0,98058,47.4563,-122.171,1610,8579
6140100875,20150415T000000,420000.0,3,1.0,1060,8097,1.0,0,0,4,7,940,120,1923,0,98133,47.7144,-122.351,1560,7940
1994200024,20141104T000000,511000.0,3,1.0,1430,3455,1.0,0,0,3,7,980,450,1947,0,98103,47.6873,-122.336,1450,4599
1324300398,20150409T000000,560000.0,3,1.0,1110,5000,1.5,0,0,3,7,1110,0,1947,0,98107,47.6550,-122.359,1420,5000
537000445,20150331T000000,282950.0,3,1.0,1250,8200,1.0,0,0,4,7,1250,0,1954,0,98003,47.3255,-122.304,1680,8633
8960000030,20140728T000000,215000.0,3,1.0,1180,7669,1.0,0,0,4,7,1180,0,1967,0,98058,47.4479,-122.176,1190,7669
2254502445,20140530T000000,385000.0,3,1.0,1220,4800,1.0,0,0,3,6,1220,0,1901,0,98122,47.6101,-122.307,1200,4800
1432600560,20141105T000000,166950.0,3,1.0,1190,8820,1.0,0,0,3,6,1190,0,1959,0,98058,47.4616,-122.184,1230,7980
3996900125,20141201T000000,230000.0,3,1.0,1060,10228,1.0,0,0,3,7,1060,0,1948,0,98155,47.7481,-122.300,1570,10228
3542300060,20150311T000000,210000.0,3,1.0,860,11725,1.0,0,0,4,6,860,0,1943,0,98056,47.5093,-122.184,1300,9514
7551300060,20140716T000000,470000.0,3,1.0,1010,5000,1.0,0,0,3,7,1010,0,1952,0,98107,47.6750,-122.394,1680,5000
3211100860,20150303T000000,274250.0,3,1.0,910,8450,1.0,0,0,4,6,910,0,1962,0,98059,47.4787,-122.158,1400,8040
7465900060,20150205T000000,425000.0,3,1.0,1010,5864,1.0,0,0,3,7,1010,0,1915,0,98116,47.5733,-122.381,1290,5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3356403400,20140724T000000,159000.0,3,1.0,1360,20000,1.0,0,0,4,7,1360,0,1953,0,98001,47.2861,-122.253,1530,9997
3832300090,20140709T000000,215000.0,3,1.0,1200,7280,1.0,0,0,4,7,1200,0,1967,0,98032,47.3724,-122.277,1200,8400
9320901250,20140910T000000,133400.0,3,1.0,900,2550,1.0,0,0,4,6,900,0,1978,0,98023,47.3036,-122.363,1120,2550
9202650040,20140926T000000,401000.0,3,1.0,1120,8321,1.0,0,0,4,6,1120,0,1941,1987,98027,47.5631,-122.091,1980,8671
1865820300,20150311T000000,205000.0,3,1.0,1120,8342,1.0,0,0,4,7,1120,0,1976,0,98042,47.3732,-122.116,1190,6660
3331500650,20140919T000000,356000.0,3,1.0,920,3863,1.0,0,0,3,6,920,0,1970,0,98118,47.5524,-122.270,1080,5150
7877400245,20140718T000000,193000.0,3,1.0,960,10761,1.0,0,0,4,6,960,0,1962,0,98002,47.2819,-122.224,960,10761
2023059052,20150504T000000,450000.0,3,1.0,1350,92721,1.0,0,0,2,6,1200,150,1946,0,98055,47.4657,-122.198,1860,8096
1431700210,20140702T000000,305000.0,3,1.0,1580,7424,1.0,0,0,3,7,1010,570,1962,0,98058,47.4607,-122.171,1710,7772
5379806155,20140910T000000,216500.0,3,1.0,1020,11652,1.0,0,0,4,6,1020,0,1971,0,98188,47.4459,-122.278,1690,11652
6381500110,20150108T000000,330000.0,3,1.0,1160,7912,1.0,0,0,4,7,1160,0,1956,0,98125,47.7336,-122.306,1190,7482
8685500145,20141230T000000,350000.0,3,1.0,1920,6710,1.0,0,0,3,7,1320,600,1959,0,98118,47.5346,-122.286,1810,5600
1775800750,20150310T000000,344000.0,3,1.0,1150,12402,1.0,0,0,4,6,1150,0,1969,0,98072,47.7422,-122.099,1400,13600
4443800705,20141008T000000,465000.0,3,1.0,910,3880,1.0,0,0,3,7,780,130,1942,0,98117,47.6862,-122.392,1220,3880
9357000230,20140822T000000,267000.0,3,1.0,940,4700,1.0,0,0,4,6,940,0,1942,0,98146,47.5117,-122.378,1020,5700
6384500535,20150326T000000,499000.0,3,1.0,1270,6250,1.0,0,0,3,7,910,360,1955,0,98116,47.5694,-122.397,2000,6250
9407000230,20141204T000000,240000.0,3,1.0,1600,12566,1.0,0,0,4,7,1600,0,1971,0,98045,47.4431,-121.765,1600,10650
4443800375,20141002T000000,400000.0,3,1.0,900,4084,1.5,0,0,3,7,900,0,1910,0,98117,47.6840,-122.393,1280,4080
4338800600,20140609T000000,235000.0,3,1.0,1590,13000,1.5,0,0,3,6,1590,0,1944,0,98166,47.4789,-122.346,1460,8400
1788800770,20140728T000000,187500.0,3,1.0,840,8400,1.0,0,0,3,6,840,0,1959,0,98023,47.3281,-122.344,1030,8640
7518507685,20150223T000000,400000.0,3,1.0,1100,5100,2.0,0,0,4,7,1100,0,1900,0,98117,47.6790,-122.386,1540,5100
522059189,20150417T000000,235000.0,3,1.0,1460,8400,1.0,0,0,3,7,1460,0,1958,0,98055,47.4243,-122.198,1460,9600
3124089060,20150424T000000,282000.0,3,1.0,1250,13503,1.5,0,0,4,6,1250,0,1931,0,98065,47.5260,-121.829,1450,13503
224059021,20141219T000000,450000.0,3,1.0,1150,35415,1.0,0,0,4,7,1010,140,1950,0,98008,47.5974,-122.129,2460,11781
7205400180,20141223T000000,235000.0,3,1.0,1240,18000,1.0,0,0,2,7,1240,0,1943,0,98198,47.3514,-122.315,1240,18000
2626119062,20141112T000000,155000.0,3,1.0,1300,6098,1.0,0,0,3,7,1300,0,2013,0,98014,47.7074,-121.364,1300,6849
3449000060,20141001T000000,320000.0,3,1.0,1400,9000,1.0,0,0,5,7,1400,0,1959,0,98059,47.5022,-122.145,1440,8400
3449000010,20150312T000000,294570.0,3,1.0,1140,8400,1.0,0,0,4,7,1140,0,1960,0,98059,47.5022,-122.144,1400,9000
522059130,20150429T000000,465000.0,3,1.0,1150,18200,1.0,0,0,5,7,1150,0,1959,0,98058,47.4262,-122.187,1714,18200
121039156,20150109T000000,249000.0,3,1.0,1030,24750,1.0,0,2,3,5,1030,0,1943,0,98023,47.3343,-122.362,2810,28800

The sample function randomly selects a number of rows from the data frame

In [12]:
df.sample(10)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
4027700666,20150426T000000,780000.0,4,2.50,3180,9603,2.0,0,2,3,9,3180,0,2002,0,98155,47.7717,-122.277,2440,15261
7856640460,20141218T000000,950000.0,4,2.75,3800,12200,2.0,0,3,4,10,3800,0,1986,0,98006,47.5689,-122.156,3710,14796
510001400,20140630T000000,765000.0,5,3.00,2870,5700,1.0,0,0,3,7,1950,920,1964,0,98103,47.6621,-122.330,1730,5529
8645540290,20141126T000000,358000.0,5,2.50,2390,8775,1.0,0,0,4,7,1270,1120,1980,0,98058,47.4639,-122.170,1800,8000
7575500040,20141212T000000,180000.0,3,1.00,1010,8863,1.0,0,0,4,6,1010,0,1990,0,98022,47.1955,-121.999,1090,8410
9274200322,20140820T000000,580000.0,3,2.50,1740,1236,3.0,0,2,3,8,1740,0,2008,0,98116,47.5891,-122.387,1740,1280
9282800065,20150329T000000,203000.0,3,1.75,1190,6000,1.0,0,0,3,7,1190,0,1952,2015,98178,47.5026,-122.236,1200,6000
3905081500,20140604T000000,532000.0,3,2.50,1820,4910,2.0,0,0,3,8,1820,0,1993,0,98029,47.5703,-121.996,2090,6668
6791050100,20140721T000000,775000.0,3,2.50,2890,8470,2.0,0,0,3,10,2890,0,1996,0,98075,47.5785,-122.054,3000,8879
7214820030,20141212T000000,475000.0,3,1.75,2020,8970,1.0,0,0,4,7,1180,840,1981,0,98072,47.7571,-122.145,2140,8008

sort_index() sorts the data frame by the index value

In [13]:
df.sort_index()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
1000102,20150422T000000,300000.0,6,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
1000102,20140916T000000,280000.0,6,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
1200019,20140508T000000,647500.0,4,1.75,2060,26036,1.0,0,0,4,8,1160,900,1947,0,98166,47.4444,-122.351,2590,21891
1200021,20140811T000000,400000.0,3,1.00,1460,43000,1.0,0,0,3,7,1460,0,1952,0,98166,47.4434,-122.347,2250,20023
2800031,20150401T000000,235000.0,3,1.00,1430,7599,1.5,0,0,4,6,1010,420,1930,0,98168,47.4783,-122.265,1290,10320
3600057,20150319T000000,402500.0,4,2.00,1650,3504,1.0,0,0,3,7,760,890,1951,2013,98144,47.5803,-122.294,1480,3504
3600072,20150330T000000,680000.0,4,2.75,2220,5310,1.0,0,0,5,7,1170,1050,1951,0,98144,47.5801,-122.294,1540,4200
3800008,20150224T000000,178000.0,5,1.50,1990,18200,1.0,0,0,3,7,1990,0,1960,0,98178,47.4938,-122.262,1860,8658
5200087,20140709T000000,487000.0,4,2.50,2540,5001,2.0,0,0,3,9,2540,0,2005,0,98108,47.5423,-122.302,2360,6834
6200017,20141112T000000,281000.0,3,1.00,1340,21336,1.5,0,0,4,5,1340,0,1945,0,98032,47.4023,-122.273,1340,37703
7200080,20141104T000000,239000.0,4,2.00,1980,10585,1.5,0,0,2,6,1980,0,1924,0,98055,47.4836,-122.214,1360,7810
7200179,20141016T000000,150000.0,2,1.00,840,12750,1.0,0,0,3,6,840,0,1925,0,98055,47.4840,-122.211,1480,6969
7200179,20150424T000000,175000.0,2,1.00,840,12750,1.0,0,0,3,6,840,0,1925,0,98055,47.4840,-122.211,1480,6969
7400062,20140521T000000,299800.0,2,1.00,790,5240,1.0,0,0,4,6,790,0,1925,0,98118,47.5303,-122.288,1430,5320
7600057,20140805T000000,520000.0,3,2.00,1410,2700,2.0,0,0,4,7,1410,0,1902,0,98122,47.6029,-122.302,1750,4000
7600065,20140605T000000,465000.0,3,2.25,1530,1245,2.0,0,0,3,9,1050,480,2014,0,98122,47.6018,-122.297,1530,2307
7600125,20141218T000000,630000.0,5,1.00,3020,4800,2.0,0,0,3,7,3020,0,1901,0,98122,47.6025,-122.313,1350,1307
7600136,20140718T000000,411000.0,2,2.00,1130,1148,2.0,0,0,3,9,800,330,2007,0,98122,47.6023,-122.314,1350,1201
9000025,20141203T000000,496000.0,2,1.00,1420,4635,2.0,0,0,4,7,1420,0,1941,1973,98115,47.6800,-122.304,1810,4635
11200070,20140721T000000,570000.0,3,2.50,1530,3296,2.0,0,0,3,8,1530,0,1998,0,98007,47.6181,-122.138,1530,4099
11200290,20140609T000000,546000.0,3,2.50,1530,3464,2.0,0,0,3,8,1530,0,1998,0,98007,47.6179,-122.141,1530,3446
11200400,20140923T000000,617000.0,3,2.50,1910,4488,2.0,0,0,3,8,1910,0,1998,0,98007,47.6176,-122.140,1530,3696
11300120,20140630T000000,635000.0,3,2.50,3350,4007,2.0,0,0,3,8,2550,800,2005,0,98034,47.7277,-122.207,2340,4167
11500240,20150428T000000,872750.0,3,2.50,2870,13695,2.0,0,0,3,10,2870,0,1991,0,98052,47.6944,-122.102,2840,8472
11500890,20150312T000000,843000.0,3,2.50,3130,8750,2.0,0,0,3,10,3130,0,1991,0,98052,47.6954,-122.103,2860,9003
11501160,20140617T000000,837700.0,5,2.75,3010,12611,2.0,0,0,3,10,3010,0,1994,0,98052,47.6960,-122.102,2890,9456
11501310,20141121T000000,715000.0,3,3.25,3060,9055,2.0,0,0,3,10,2460,600,1994,0,98052,47.6971,-122.101,2990,9598
11501330,20140902T000000,795000.0,3,3.50,3190,10223,2.0,0,0,3,10,2560,630,1994,0,98052,47.6968,-122.102,3120,9735
11510310,20140905T000000,835000.0,4,2.75,3130,13412,2.0,0,0,3,9,2140,990,1993,0,98052,47.6993,-122.102,2260,9984
11510700,20140519T000000,755000.0,4,2.50,2660,10452,2.0,0,0,3,9,2660,0,1993,0,98052,47.6972,-122.104,2890,9025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9834200925,20140910T000000,330000.0,3,2.25,1340,4080,1.5,0,0,3,6,1170,170,1907,0,98144,47.5722,-122.291,1670,4080
9834200950,20140616T000000,385000.0,4,1.75,1690,4080,1.0,0,0,4,7,870,820,1984,0,98144,47.5720,-122.289,1320,4080
9834200975,20150210T000000,495000.0,3,3.00,1520,4080,2.0,0,0,5,7,1520,0,1948,0,98144,47.5720,-122.290,1320,4080
9834201100,20141222T000000,332500.0,4,2.00,1440,4855,2.0,0,0,4,7,1440,0,1972,0,98144,47.5717,-122.287,1300,4080
9834201145,20150222T000000,635000.0,4,2.50,2880,3091,2.0,0,0,3,9,1940,940,2014,0,98144,47.5711,-122.286,1560,4080
9834201205,20150304T000000,385000.0,1,1.00,620,5100,1.0,0,0,3,6,620,0,1954,0,98144,47.5699,-122.287,1540,2676
9834201215,20141009T000000,276000.0,2,1.00,870,2676,1.0,0,0,3,7,820,50,2004,0,98144,47.5702,-122.287,1500,1719
9834201366,20141216T000000,429900.0,3,2.00,1490,1286,3.0,0,0,3,8,1490,0,2014,0,98144,47.5700,-122.288,1420,1230
9834201367,20150126T000000,429000.0,3,2.00,1490,1126,3.0,0,0,3,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
9834201370,20150417T000000,430100.0,3,2.25,1400,1078,2.0,0,0,3,8,940,460,2009,0,98144,47.5701,-122.288,1420,1230
9834201375,20150206T000000,425000.0,3,2.25,1420,1230,2.0,0,0,3,8,940,480,2009,0,98144,47.5703,-122.288,1400,1230
9834201470,20141218T000000,303000.0,2,1.50,1000,1075,2.0,0,0,3,7,840,160,2007,0,98144,47.5708,-122.288,1000,1083
9835800320,20140828T000000,300000.0,4,1.75,2080,8750,1.0,0,0,4,8,1330,750,1967,0,98032,47.3749,-122.291,1790,8750
9835800750,20141203T000000,247000.0,3,2.25,1640,7630,1.0,0,0,4,8,1180,460,1968,0,98032,47.3739,-122.290,1930,7630
9835800840,20150204T000000,215000.0,4,2.00,1470,7000,1.0,0,0,4,8,1470,0,1967,0,98032,47.3742,-122.289,1640,7000
9835801000,20140625T000000,245700.0,3,2.25,1640,8400,1.0,0,0,3,8,1180,460,1968,0,98032,47.3733,-122.289,1600,8120
9839300125,20150107T000000,575000.0,4,2.00,1810,4400,2.0,0,0,3,8,1700,110,1909,0,98122,47.6132,-122.292,1470,4400
9839300285,20150412T000000,720000.0,3,2.50,2100,2200,2.0,0,0,4,7,1500,600,1919,0,98122,47.6140,-122.294,1750,4400
9839300545,20140714T000000,605000.0,2,2.00,1270,5500,1.5,0,0,4,8,1270,0,1921,0,98122,47.6121,-122.294,1870,4400
9839300775,20140710T000000,655000.0,4,2.25,2170,4080,2.0,0,0,3,7,1920,250,1980,0,98122,47.6124,-122.293,1890,4400
9839300875,20140514T000000,800000.0,3,1.00,1700,4400,1.5,0,0,4,8,1700,0,1906,0,98122,47.6120,-122.292,1610,4180
9839301055,20140626T000000,670000.0,3,1.50,1490,4400,1.5,0,0,4,7,1490,0,1906,0,98122,47.6113,-122.292,1560,4400
9839301060,20150406T000000,650500.0,3,1.75,1740,4400,1.5,0,0,3,8,1740,0,1903,0,98122,47.6115,-122.292,1740,4400
9839301165,20141001T000000,998500.0,2,1.00,1570,4400,1.5,0,0,4,8,1570,0,1914,0,98122,47.6112,-122.293,1850,4400
9842300036,20141008T000000,415885.0,3,1.00,1310,4163,1.0,0,0,4,7,1310,0,1964,0,98126,47.5301,-122.381,1120,4166
9842300095,20140725T000000,365000.0,5,2.00,1600,4168,1.5,0,0,3,7,1600,0,1927,0,98126,47.5297,-122.381,1190,4168
9842300485,20150311T000000,380000.0,2,1.00,1040,7372,1.0,0,0,5,7,840,200,1939,0,98126,47.5285,-122.378,1930,5150
9842300540,20140624T000000,339000.0,3,1.00,1100,4128,1.0,0,0,4,7,720,380,1942,0,98126,47.5296,-122.379,1510,4538
9895000040,20140703T000000,399900.0,2,1.75,1410,1005,1.5,0,0,3,9,900,510,2011,0,98027,47.5446,-122.018,1440,1188
9900000190,20141030T000000,268950.0,3,1.00,1320,8100,1.0,0,0,3,6,880,440,1943,0,98166,47.4697,-122.351,1000,8100

sort_values() orders the dataframe by a specific column value

In [14]:
df.sort_values(['bedrooms'])

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
3374500520,20150429T000000,355000.0,0,0.00,2460,8049,2.0,0,0,3,8,2460,0,1990,0,98031,47.4095,-122.168,2520,8050
2954400190,20140624T000000,1295650.0,0,0.00,4810,28008,2.0,0,0,3,12,4810,0,1990,0,98053,47.6642,-122.069,4740,35061
7849202190,20141223T000000,235000.0,0,0.00,1470,4800,2.0,0,0,3,7,1470,0,1996,0,98065,47.5265,-121.828,1060,7200
3980300371,20140926T000000,142000.0,0,0.00,290,20875,1.0,0,0,1,1,290,0,1963,0,98024,47.5308,-121.888,1620,22850
9543000205,20150413T000000,139950.0,0,0.00,844,4269,1.0,0,0,4,7,844,0,1913,0,98001,47.2781,-122.250,1380,9600
6896300380,20141002T000000,228000.0,0,1.00,390,5900,1.0,0,0,2,4,390,0,1953,0,98118,47.5260,-122.261,2170,6000
2569500210,20141117T000000,339950.0,0,2.50,2290,8319,2.0,0,0,3,8,2290,0,1985,0,98042,47.3473,-122.151,2500,8751
2310060040,20140925T000000,240000.0,0,2.50,1810,5669,2.0,0,0,3,7,1810,0,2003,0,98038,47.3493,-122.053,1810,5685
6306400140,20140612T000000,1095000.0,0,0.00,3064,4764,3.5,0,2,3,7,3064,0,1990,0,98102,47.6362,-122.322,2360,4000
1453602309,20140805T000000,288000.0,0,1.50,1430,1650,3.0,0,0,3,7,1430,0,1999,0,98125,47.7222,-122.290,1430,1650
7849202299,20150218T000000,320000.0,0,2.50,1490,7111,2.0,0,0,3,7,1490,0,1999,0,98065,47.5261,-121.826,1500,4675
1222029077,20141029T000000,265000.0,0,0.75,384,213444,1.0,0,0,3,4,384,0,2003,0,98070,47.4177,-122.491,1920,224341
3918400017,20150205T000000,380000.0,0,0.00,1470,979,3.0,0,2,3,8,1470,0,2006,0,98133,47.7145,-122.356,1470,1399
6430500191,20141106T000000,315000.0,1,1.00,700,3876,1.0,0,0,3,6,700,0,1910,0,98103,47.6886,-122.352,1150,3952
4356200120,20141023T000000,248000.0,1,1.00,790,12000,1.0,0,0,3,6,790,0,1918,0,98118,47.5146,-122.265,1900,6000
7550800916,20140602T000000,395000.0,1,1.00,730,3000,1.0,0,0,3,7,730,0,1911,0,98107,47.6741,-122.396,1520,5000
1972201161,20150323T000000,435000.0,1,1.00,670,1800,1.0,0,0,5,6,670,0,1905,0,98103,47.6540,-122.350,1330,3360
1172000150,20140829T000000,238000.0,1,1.00,530,6350,1.0,0,0,5,5,530,0,1941,0,98103,47.6946,-122.357,1200,6350
2025079033,20141210T000000,415000.0,1,2.00,3000,204732,2.5,0,2,3,8,3000,0,1979,0,98014,47.6331,-121.945,2330,213008
1735800050,20150409T000000,142500.0,1,1.00,690,6825,1.0,0,0,4,5,690,0,1917,0,98002,47.3109,-122.225,1330,5381
1221000395,20140507T000000,250000.0,1,1.00,1100,4373,1.0,0,0,2,6,820,280,1947,0,98166,47.4653,-122.338,1100,7500
2123039032,20141027T000000,369900.0,1,0.75,760,10079,1.0,1,4,5,5,760,0,1936,0,98070,47.4683,-122.438,1230,14267
5652601075,20140825T000000,377000.0,1,1.00,950,10585,1.5,0,0,3,6,950,0,1929,0,98115,47.6968,-122.297,1400,7056
2144800615,20140625T000000,190000.0,1,0.75,930,29258,1.0,0,0,3,6,930,0,1941,0,98178,47.4837,-122.236,2000,18321
5016000315,20140616T000000,332000.0,1,1.00,960,2640,1.0,0,0,3,7,760,200,1908,0,98112,47.6223,-122.294,1620,3759
7841300285,20140811T000000,199950.0,1,1.50,1048,4800,1.0,0,0,3,7,1048,0,1942,0,98055,47.4759,-122.212,950,4800
726059047,20141216T000000,310000.0,1,1.00,920,8282,1.5,0,0,3,6,920,0,1944,1980,98011,47.7610,-122.214,2260,14025
537000130,20140908T000000,360000.0,1,2.25,2060,10600,1.5,0,0,3,7,1560,500,1927,1983,98003,47.3291,-122.304,2060,11880
7950304095,20150217T000000,257500.0,1,1.00,710,6060,1.0,0,0,4,6,710,0,1916,0,98118,47.5621,-122.283,1440,4545
126039305,20141013T000000,345000.0,1,1.00,540,10125,1.0,0,0,3,5,540,0,1961,0,98177,47.7739,-122.358,1840,10125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2616800600,20140530T000000,840000.0,7,4.50,4290,37607,1.5,0,0,5,10,4290,0,1982,0,98027,47.4812,-122.033,2810,40510
4040500100,20141020T000000,539000.0,7,2.25,2620,6890,2.0,0,0,4,7,2620,0,1961,0,98007,47.6123,-122.134,2070,7910
9175600025,20141007T000000,800000.0,7,6.75,7480,41664,2.0,0,2,3,11,5080,2400,1953,0,98166,47.4643,-122.368,2810,33190
7227802030,20140623T000000,350000.0,7,3.00,2800,9569,1.0,0,2,3,7,1400,1400,1963,0,98056,47.5102,-122.183,2150,7333
9187200345,20140709T000000,599000.0,7,2.50,2580,5750,1.0,0,0,4,7,1880,700,1901,0,98122,47.6025,-122.294,2280,5750
5561300480,20150408T000000,600000.0,7,2.25,3170,36384,2.0,0,0,3,8,3170,0,1969,0,98027,47.4654,-122.003,2460,38370
9126101740,20141204T000000,490000.0,8,5.00,2800,2580,2.0,0,0,3,8,1880,920,1997,0,98122,47.6086,-122.303,1800,2580
685000115,20141007T000000,2150000.0,8,6.00,4340,9415,2.0,0,0,3,8,4340,0,1967,0,98004,47.6316,-122.202,2050,9100
7418000130,20141211T000000,430000.0,8,3.25,4300,10441,2.0,0,0,4,8,2800,1500,1979,0,98059,47.4786,-122.131,1780,10457
1346300150,20141020T000000,3300000.0,8,4.00,7710,11750,3.5,0,0,5,12,6090,1620,1904,0,98112,47.6263,-122.314,4210,8325
6746700615,20150318T000000,700000.0,8,2.50,2280,3000,1.5,0,0,3,7,1210,1070,1911,0,98105,47.6675,-122.316,1610,3000
2769600590,20141016T000000,900000.0,8,4.00,4020,7500,1.0,0,0,3,8,2010,2010,1968,0,98107,47.6732,-122.363,1560,3737
1873400020,20140703T000000,340000.0,8,2.75,2790,6695,1.0,0,0,3,7,1470,1320,1977,0,98133,47.7565,-122.331,1760,7624
1338600225,20140528T000000,1970000.0,8,3.50,4440,6480,2.0,0,3,5,10,3140,1300,1959,0,98112,47.6310,-122.303,4440,8640
8813400155,20141219T000000,808000.0,8,3.75,3460,4600,2.0,0,0,3,7,2860,600,1987,0,98105,47.6617,-122.289,2170,3750
3756900027,20141125T000000,575000.0,8,3.00,3840,15990,1.0,0,0,3,7,2530,1310,1961,0,98034,47.7111,-122.211,1380,8172
8141200080,20140814T000000,680000.0,8,2.75,2530,4800,2.0,0,0,4,7,1390,1140,1901,0,98112,47.6241,-122.305,1540,4800
7226500100,20150219T000000,373000.0,8,3.00,2850,12714,1.0,0,0,3,7,2850,0,1959,0,98055,47.4859,-122.205,1480,4942
1652500060,20140711T000000,1650000.0,8,2.75,4040,20666,1.0,0,0,4,9,2020,2020,1962,0,98004,47.6340,-122.221,3670,20500
2902200015,20150106T000000,700000.0,9,3.00,3680,4400,2.0,0,0,3,7,2830,850,1908,0,98102,47.6374,-122.324,1960,2450
8823900290,20150317T000000,1400000.0,9,4.00,4620,5508,2.5,0,0,3,11,3870,750,1915,0,98105,47.6684,-122.309,2710,4320
8823901445,20150313T000000,934000.0,9,3.00,2820,4480,2.0,0,0,3,7,1880,940,1918,0,98105,47.6654,-122.307,2460,4400
9822700190,20140808T000000,1280000.0,9,4.50,3650,5000,2.0,0,0,3,8,2530,1120,1915,2010,98105,47.6604,-122.289,2510,5000
424049043,20140811T000000,450000.0,9,7.50,4050,6504,2.0,0,0,3,7,4050,0,1996,0,98144,47.5923,-122.301,1448,3866
1997200215,20140507T000000,599999.0,9,4.50,3830,6988,2.5,0,0,3,7,2450,1380,1938,0,98103,47.6927,-122.338,1460,6291
5566100170,20141029T000000,650000.0,10,2.00,3610,11914,2.0,0,0,4,7,3010,600,1958,0,98006,47.5705,-122.175,2040,11914
627300145,20140814T000000,1148000.0,10,5.25,4590,10920,1.0,0,2,3,9,2500,2090,2008,0,98004,47.5861,-122.113,2730,10400
8812401450,20141229T000000,660000.0,10,3.00,2920,3745,2.0,0,0,4,7,1860,1060,1913,0,98105,47.6635,-122.320,1810,3745
1773100755,20140821T000000,520000.0,11,3.00,3000,4960,2.0,0,0,3,7,2400,600,1918,1999,98106,47.5560,-122.363,1420,4960
2402100895,20140625T000000,640000.0,33,1.75,1620,6000,1.0,0,0,5,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700

In [15]:
df.sort_values(['bedrooms'], ascending = False)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
2402100895,20140625T000000,640000.0,33,1.75,1620,6000,1.0,0,0,5,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700
1773100755,20140821T000000,520000.0,11,3.00,3000,4960,2.0,0,0,3,7,2400,600,1918,1999,98106,47.5560,-122.363,1420,4960
5566100170,20141029T000000,650000.0,10,2.00,3610,11914,2.0,0,0,4,7,3010,600,1958,0,98006,47.5705,-122.175,2040,11914
627300145,20140814T000000,1148000.0,10,5.25,4590,10920,1.0,0,2,3,9,2500,2090,2008,0,98004,47.5861,-122.113,2730,10400
8812401450,20141229T000000,660000.0,10,3.00,2920,3745,2.0,0,0,4,7,1860,1060,1913,0,98105,47.6635,-122.320,1810,3745
424049043,20140811T000000,450000.0,9,7.50,4050,6504,2.0,0,0,3,7,4050,0,1996,0,98144,47.5923,-122.301,1448,3866
1997200215,20140507T000000,599999.0,9,4.50,3830,6988,2.5,0,0,3,7,2450,1380,1938,0,98103,47.6927,-122.338,1460,6291
2902200015,20150106T000000,700000.0,9,3.00,3680,4400,2.0,0,0,3,7,2830,850,1908,0,98102,47.6374,-122.324,1960,2450
8823900290,20150317T000000,1400000.0,9,4.00,4620,5508,2.5,0,0,3,11,3870,750,1915,0,98105,47.6684,-122.309,2710,4320
9822700190,20140808T000000,1280000.0,9,4.50,3650,5000,2.0,0,0,3,8,2530,1120,1915,2010,98105,47.6604,-122.289,2510,5000
8823901445,20150313T000000,934000.0,9,3.00,2820,4480,2.0,0,0,3,7,1880,940,1918,0,98105,47.6654,-122.307,2460,4400
2769600590,20141016T000000,900000.0,8,4.00,4020,7500,1.0,0,0,3,8,2010,2010,1968,0,98107,47.6732,-122.363,1560,3737
1652500060,20140711T000000,1650000.0,8,2.75,4040,20666,1.0,0,0,4,9,2020,2020,1962,0,98004,47.6340,-122.221,3670,20500
1338600225,20140528T000000,1970000.0,8,3.50,4440,6480,2.0,0,3,5,10,3140,1300,1959,0,98112,47.6310,-122.303,4440,8640
7418000130,20141211T000000,430000.0,8,3.25,4300,10441,2.0,0,0,4,8,2800,1500,1979,0,98059,47.4786,-122.131,1780,10457
3756900027,20141125T000000,575000.0,8,3.00,3840,15990,1.0,0,0,3,7,2530,1310,1961,0,98034,47.7111,-122.211,1380,8172
7226500100,20150219T000000,373000.0,8,3.00,2850,12714,1.0,0,0,3,7,2850,0,1959,0,98055,47.4859,-122.205,1480,4942
8141200080,20140814T000000,680000.0,8,2.75,2530,4800,2.0,0,0,4,7,1390,1140,1901,0,98112,47.6241,-122.305,1540,4800
1873400020,20140703T000000,340000.0,8,2.75,2790,6695,1.0,0,0,3,7,1470,1320,1977,0,98133,47.7565,-122.331,1760,7624
6746700615,20150318T000000,700000.0,8,2.50,2280,3000,1.5,0,0,3,7,1210,1070,1911,0,98105,47.6675,-122.316,1610,3000
1346300150,20141020T000000,3300000.0,8,4.00,7710,11750,3.5,0,0,5,12,6090,1620,1904,0,98112,47.6263,-122.314,4210,8325
8813400155,20141219T000000,808000.0,8,3.75,3460,4600,2.0,0,0,3,7,2860,600,1987,0,98105,47.6617,-122.289,2170,3750
9126101740,20141204T000000,490000.0,8,5.00,2800,2580,2.0,0,0,3,8,1880,920,1997,0,98122,47.6086,-122.303,1800,2580
685000115,20141007T000000,2150000.0,8,6.00,4340,9415,2.0,0,0,3,8,4340,0,1967,0,98004,47.6316,-122.202,2050,9100
2771604190,20140617T000000,824000.0,7,4.25,3670,4000,2.0,0,1,3,8,2800,870,1964,0,98199,47.6375,-122.388,2010,4000
6453300306,20140910T000000,419000.0,7,3.25,4340,8521,2.0,0,0,3,7,2550,1790,1986,0,98106,47.5200,-122.338,1890,8951
5536100005,20140808T000000,2300000.0,7,4.75,5310,8816,2.0,0,0,3,10,3650,1660,2013,0,98004,47.6221,-122.208,2920,10610
4178300130,20150413T000000,950000.0,7,3.50,3470,16264,2.0,0,0,4,9,3470,0,1980,0,98007,47.6203,-122.149,3040,13500
2818600010,20150314T000000,1185000.0,7,3.50,3890,8342,2.0,0,4,3,9,2840,1050,1968,0,98117,47.7011,-122.392,2870,8342
2887950020,20140625T000000,280000.0,7,2.50,1940,5458,2.0,0,0,3,7,1940,0,1994,0,98092,47.3191,-122.177,1710,5688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6450301220,20140916T000000,264000.0,1,1.00,710,4725,1.0,0,0,3,6,710,0,1939,0,98133,47.7328,-122.340,900,5250
1022049182,20150428T000000,175000.0,1,1.00,620,8685,1.0,0,0,4,5,620,0,1976,0,98198,47.4095,-122.290,1300,12150
7950302150,20150410T000000,385000.0,1,1.00,660,3570,1.0,0,0,3,6,660,0,1906,0,98118,47.5659,-122.284,1520,4080
2461900845,20140903T000000,310000.0,1,1.00,570,6000,1.0,0,0,2,5,570,0,1918,0,98136,47.5517,-122.385,1530,6000
4047200825,20141011T000000,400000.0,1,1.00,1390,60984,1.0,0,0,3,6,1390,0,1960,0,98019,47.7652,-121.903,1620,24225
2658000115,20140618T000000,190000.0,1,1.00,720,4800,1.0,0,0,3,6,720,0,1914,0,98118,47.5303,-122.270,1240,4860
6450304600,20141023T000000,315000.0,1,2.25,1940,2550,2.0,0,0,4,7,1100,840,1979,0,98133,47.7313,-122.343,1580,5100
1931300955,20141126T000000,525000.0,1,1.00,830,3200,1.0,0,0,3,7,830,0,1924,0,98103,47.6557,-122.348,1350,2512
5101405604,20140814T000000,350000.0,1,1.00,900,6380,1.0,0,0,3,6,900,0,1947,0,98125,47.7019,-122.311,1830,6380
726059047,20141216T000000,310000.0,1,1.00,920,8282,1.5,0,0,3,6,920,0,1944,1980,98011,47.7610,-122.214,2260,14025
7544800195,20140813T000000,415000.0,1,1.00,760,3000,1.0,0,0,3,7,760,0,1900,0,98122,47.6059,-122.303,1270,3000
985001015,20140604T000000,135000.0,1,1.00,790,13062,1.0,0,0,3,6,790,0,1942,0,98168,47.4919,-122.311,1240,7137
3023039231,20140714T000000,650000.0,1,1.00,920,91476,1.5,0,0,3,6,920,0,1996,2002,98070,47.4480,-122.472,1746,91476
8807900236,20141219T000000,430000.0,1,1.00,630,1362,1.0,0,0,3,7,630,0,1943,0,98109,47.6342,-122.342,1090,1376
461002551,20141004T000000,330600.0,1,1.00,580,1799,1.0,0,0,3,7,580,0,1908,2005,98117,47.6829,-122.375,1260,4000
5101405604,20150428T000000,395000.0,1,1.00,900,6380,1.0,0,0,3,6,900,0,1947,0,98125,47.7019,-122.311,1830,6380
1112000125,20140930T000000,463500.0,1,1.00,1090,8750,1.0,0,0,4,6,1090,0,1924,0,98118,47.5400,-122.269,1830,5000
3918400017,20150205T000000,380000.0,0,0.00,1470,979,3.0,0,2,3,8,1470,0,2006,0,98133,47.7145,-122.356,1470,1399
1222029077,20141029T000000,265000.0,0,0.75,384,213444,1.0,0,0,3,4,384,0,2003,0,98070,47.4177,-122.491,1920,224341
2954400190,20140624T000000,1295650.0,0,0.00,4810,28008,2.0,0,0,3,12,4810,0,1990,0,98053,47.6642,-122.069,4740,35061
7849202190,20141223T000000,235000.0,0,0.00,1470,4800,2.0,0,0,3,7,1470,0,1996,0,98065,47.5265,-121.828,1060,7200
6896300380,20141002T000000,228000.0,0,1.00,390,5900,1.0,0,0,2,4,390,0,1953,0,98118,47.5260,-122.261,2170,6000
9543000205,20150413T000000,139950.0,0,0.00,844,4269,1.0,0,0,4,7,844,0,1913,0,98001,47.2781,-122.250,1380,9600
7849202299,20150218T000000,320000.0,0,2.50,1490,7111,2.0,0,0,3,7,1490,0,1999,0,98065,47.5261,-121.826,1500,4675
1453602309,20140805T000000,288000.0,0,1.50,1430,1650,3.0,0,0,3,7,1430,0,1999,0,98125,47.7222,-122.290,1430,1650
3980300371,20140926T000000,142000.0,0,0.00,290,20875,1.0,0,0,1,1,290,0,1963,0,98024,47.5308,-121.888,1620,22850
2310060040,20140925T000000,240000.0,0,2.50,1810,5669,2.0,0,0,3,7,1810,0,2003,0,98038,47.3493,-122.053,1810,5685
6306400140,20140612T000000,1095000.0,0,0.00,3064,4764,3.5,0,2,3,7,3064,0,1990,0,98102,47.6362,-122.322,2360,4000
2569500210,20141117T000000,339950.0,0,2.50,2290,8319,2.0,0,0,3,8,2290,0,1985,0,98042,47.3473,-122.151,2500,8751
3374500520,20150429T000000,355000.0,0,0.00,2460,8049,2.0,0,0,3,8,2460,0,1990,0,98031,47.4095,-122.168,2520,8050

## Dataframe computations

In [16]:
import seaborn as sns

In [17]:
group_df = df.groupby('bedrooms')

In [18]:
type(group_df)

pandas.core.groupby.groupby.DataFrameGroupBy

In [19]:
group_df.head(2)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
9212900260,20140527T000000,468000.0,2,1.00,1160,6000,1.0,0,0,4,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
1175000570,20150312T000000,530000.0,5,2.00,1810,4850,1.5,0,0,3,7,1810,0,1900,0,98107,47.6700,-122.394,1360,4850
7137970340,20140703T000000,285000.0,5,2.50,2270,6300,2.0,0,0,3,8,2270,0,1995,0,98092,47.3266,-122.169,2240,7005
7920100045,20140516T000000,350000.0,1,1.00,700,5100,1.0,0,0,3,7,700,0,1942,0,98115,47.6790,-122.300,1010,5100
6300000550,20140717T000000,464000.0,6,3.00,2300,3404,2.0,0,0,3,7,1600,700,1920,1994,98133,47.7067,-122.343,1560,1312
9264902050,20141121T000000,315000.0,6,2.75,2940,7350,1.0,0,0,3,8,1780,1160,1978,0,98023,47.3103,-122.339,2120,8236
2123039032,20141027T000000,369900.0,1,0.75,760,10079,1.0,1,4,5,5,760,0,1936,0,98070,47.4683,-122.438,1230,14267
5486800070,20140620T000000,1950000.0,7,3.50,4640,15235,2.0,0,1,3,11,2860,1780,1965,2003,98040,47.5666,-122.231,3230,20697
6306400140,20140612T000000,1095000.0,0,0.00,3064,4764,3.5,0,2,3,7,3064,0,1990,0,98102,47.6362,-122.322,2360,4000
4024100951,20150105T000000,420000.0,7,3.00,2940,8624,1.0,0,0,3,8,1690,1250,1977,0,98155,47.7555,-122.307,1850,8031
9126101740,20141204T000000,490000.0,8,5.00,2800,2580,2.0,0,0,3,8,1880,920,1997,0,98122,47.6086,-122.303,1800,2580
3918400017,20150205T000000,380000.0,0,0.00,1470,979,3.0,0,2,3,8,1470,0,2006,0,98133,47.7145,-122.356,1470,1399
685000115,20141007T000000,2150000.0,8,6.00,4340,9415,2.0,0,0,3,8,4340,0,1967,0,98004,47.6316,-122.202,2050,9100
1997200215,20140507T000000,599999.0,9,4.50,3830,6988,2.5,0,0,3,7,2450,1380,1938,0,98103,47.6927,-122.338,1460,6291
2902200015,20150106T000000,700000.0,9,3.00,3680,4400,2.0,0,0,3,7,2830,850,1908,0,98102,47.6374,-122.324,1960,2450
1773100755,20140821T000000,520000.0,11,3.00,3000,4960,2.0,0,0,3,7,2400,600,1918,1999,98106,47.5560,-122.363,1420,4960
627300145,20140814T000000,1148000.0,10,5.25,4590,10920,1.0,0,2,3,9,2500,2090,2008,0,98004,47.5861,-122.113,2730,10400
5566100170,20141029T000000,650000.0,10,2.00,3610,11914,2.0,0,0,4,7,3010,600,1958,0,98006,47.5705,-122.175,2040,11914
2402100895,20140625T000000,640000.0,33,1.75,1620,6000,1.0,0,0,5,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700

once the dataframe has been grouped by a specific column, it is possible to perform mathematical requests to gain insights about a particular group.

In [20]:
group_df.median()

,price,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
bedrooms,,,,,,,,,,,,,,,,,,
0,288000.0,0.00,1470.0,5900.0,2.0,0.0,0.0,3.0,7.0,1470.0,0.0,1990.0,0.0,98065.0,47.52610,-122.168,1810.0,7200.0
1,299000.0,1.00,780.0,5750.0,1.0,0.0,0.0,3.0,6.0,760.0,0.0,1940.0,0.0,98116.0,47.56210,-122.315,1360.0,5650.0
2,374000.0,1.00,1140.0,5244.0,1.0,0.0,0.0,3.0,7.0,1010.0,0.0,1948.0,0.0,98116.0,47.60285,-122.316,1430.0,5400.0
3,413000.0,2.00,1680.0,7629.5,1.0,0.0,0.0,3.0,7.0,1440.0,0.0,1976.0,0.0,98059.0,47.56505,-122.231,1720.0,7688.5
4,549997.5,2.50,2410.0,8100.0,2.0,0.0,0.0,3.0,8.0,2080.0,0.0,1980.0,0.0,98056.0,47.57110,-122.192,2190.0,8000.0
5,620000.0,2.75,2870.0,8925.0,2.0,0.0,0.0,3.0,8.0,2190.0,700.0,1975.0,0.0,98056.0,47.58310,-122.209,2280.0,8550.0
6,650000.0,3.00,2955.0,8696.0,2.0,0.0,0.0,3.0,8.0,2340.0,885.0,1966.0,0.0,98097.0,47.60245,-122.269,2095.0,8241.0
7,728580.0,3.50,3335.0,8836.0,2.0,0.0,0.0,3.0,8.0,2820.0,750.0,1964.5,0.0,98104.0,47.62120,-122.282,2215.0,8088.0
8,700000.0,3.25,3840.0,7500.0,2.0,0.0,0.0,3.0,8.0,2530.0,1300.0,1962.0,0.0,98105.0,47.63160,-122.303,1780.0,7624.0
9,817000.0,4.25,3755.0,5254.0,2.0,0.0,0.0,3.0,7.0,2680.0,895.0,1916.5,0.0,98105.0,47.66290,-122.308,2210.0,4360.0
10,660000.0,3.00,3610.0,10920.0,2.0,0.0,0.0,4.0,7.0,2500.0,1060.0,1958.0,0.0,98006.0,47.58610,-122.175,2040.0,10400.0
11,520000.0,3.00,3000.0,4960.0,2.0,0.0,0.0,3.0,7.0,2400.0,600.0,1918.0,1999.0,98106.0,47.55600,-122.363,1420.0,4960.0
33,640000.0,1.75,1620.0,6000.0,1.0,0.0,0.0,5.0,7.0,1040.0,580.0,1947.0,0.0,98103.0,47.68780,-122.331,1330.0,4700.0

In [21]:
group_df.std()

,price,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
bedrooms,,,,,,,,,,,,,,,,,,
0,358682.627507,1.067438,1253.700778,57388.490632,0.828189,0.000000,0.751068,0.688737,2.594373,1253.700778,0.000000,26.381326,0.000000,41.557961,0.145040,0.208930,934.499729,60292.876198
1,148864.955017,0.363626,389.426470,46679.744805,0.369120,0.156901,0.843677,0.741567,1.128130,304.247873,187.395586,29.255444,556.485064,49.630370,0.123099,0.176073,407.588020,35664.464995
2,198051.827269,0.540169,463.876000,47739.592315,0.538017,0.105403,0.677109,0.665750,0.943991,376.858801,261.491067,32.280334,393.972484,47.419698,0.117607,0.131554,423.513515,25795.371242
3,262469.771863,0.629864,623.118916,35652.545246,0.561893,0.080454,0.685245,0.640348,0.949856,573.570701,351.443102,27.222798,382.064452,53.724672,0.146264,0.144433,541.362922,27249.179317
4,388594.441911,0.646521,823.977593,45758.151730,0.485023,0.076022,0.813915,0.651028,1.207044,856.965023,484.590608,28.259594,408.076302,51.665516,0.138538,0.134530,717.011186,28511.479477
5,596204.003693,0.835774,1074.759366,42469.256575,0.491869,0.108324,0.990331,0.661486,1.341003,1055.781060,612.940345,29.789835,437.940779,53.601705,0.120346,0.122936,810.696482,20848.065131
6,799238.819958,1.065419,1294.411179,38054.283093,0.536175,0.120595,1.167630,0.681232,1.374814,1119.763491,674.875042,29.657182,555.693007,54.738548,0.120704,0.108627,811.522085,34100.083352
7,739953.558961,1.385908,2049.383073,48883.791261,0.502660,0.000000,1.059066,0.685659,1.501303,1518.962104,924.339178,29.757149,622.422090,53.339735,0.095969,0.117085,824.400640,34819.366375
8,897495.725295,1.011156,1393.688153,5296.854484,0.722797,0.000000,0.832050,0.776250,1.497862,1338.602888,640.461572,31.236689,0.000000,45.012676,0.076958,0.067218,1083.994276,4734.568010
9,381533.900984,1.655798,588.107133,1069.600299,0.258199,0.000000,0.000000,0.000000,1.602082,853.317057,467.717864,33.109918,820.579064,16.378848,0.034494,0.017328,552.024154,1267.205495
10,284677.595419,1.664582,839.186114,4457.226754,0.577350,0.000000,1.154701,0.577350,1.154701,576.223336,762.954782,47.521925,0.000000,57.743687,0.049805,0.106237,478.783180,4345.760041
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
group_df.aggregate(['mean', 'std'])

                 price                bathrooms            sqft_living  \
                  mean            std      mean       std         mean
bedrooms
0         4.095038e+05  358682.627507  0.826923  1.067438  1707.846154
1         3.176429e+05  148864.955017  1.066583  0.363626   884.613065
2         4.013727e+05  198051.827269  1.401721  0.540169  1239.752899
3         4.662321e+05  262469.771863  1.968394  0.629864  1805.837235
4         6.354195e+05  388594.441911  2.436428  0.646521  2554.649666
5         7.865998e+05  596204.003693  2.778576  0.835774  3047.545284
6         8.255206e+05  799238.819958  3.068015  1.065419  3284.341912
7         9.511847e+05  739953.558961  3.651316  1.385908  3974.210526
8         1.105077e+06  897495.725295  3.557692  1.011156  3800.000000
9         8.939998e+05  381533.900984  4.416667  1.655798  3775.000000
10        8.193333e+05  284677.595419  3.416667  1.664582  3706.666667
11        5.200000e+05            NaN  3.000000       NaN  3000.000000
33        6.400000e+05            NaN  1.750000       NaN  1620.000000

                           sqft_lot                  floors            \
                  std          mean           std      mean       std
bedrooms
0         1253.700778  24141.307692  57388.490632  1.961538  0.828189
1          389.426470  16285.673367  46679.744805  1.150754  0.369120
2          463.876000  12096.726087  47739.592315  1.306703  0.538017
3          623.118916  14414.790208  35652.545246  1.449410  0.561893
4          823.977593  16720.793374  45758.151730  1.616100  0.485023
5         1074.759366  16769.022486  42469.256575  1.579638  0.491869
6         1294.411179  18586.930147  38054.283093  1.606618  0.536175
7         2049.383073  20840.552632  48883.791261  1.723684  0.502660
8         1393.688153   8971.615385   5296.854484  1.692308  0.722797
9          588.107133   5480.000000   1069.600299  2.166667  0.258199
10         839.186114   8859.666667   4457.226754  1.666667  0.577350
11                NaN   4960.000000           NaN  2.000000       NaN
33                NaN   6000.000000           NaN  1.000000       NaN

              ...            zipcode                   lat            \
              ...               mean        std       mean       std
bedrooms      ...
0             ...       98066.692308  41.557961  47.511415  0.145040
1             ...       98103.417085  49.630370  47.567169  0.123099
2             ...       98105.953623  47.419698  47.588601  0.117607
3             ...       98076.478217  53.724672  47.551478  0.146264
4             ...       98069.749201  51.665516  47.556118  0.138538
5             ...       98070.188007  53.601705  47.574169  0.120346
6             ...       98079.463235  54.738548  47.580421  0.120704
7             ...       98085.815789  53.339735  47.609024  0.095969
8             ...       98081.846154  45.012676  47.630008  0.076958
9             ...       98110.666667  16.378848  47.652767  0.034494
10            ...       98038.333333  57.743687  47.606700  0.049805
11            ...       98106.000000        NaN  47.556000       NaN
33            ...       98103.000000        NaN  47.687800       NaN

                long           sqft_living15                 sqft_lot15  \
                mean       std          mean          std          mean
bedrooms
0        -122.150231  0.208930   2036.923077   934.499729  26097.076923
1        -122.256854  0.176073   1449.567839   407.588020  14240.221106
2        -122.278570  0.131554   1503.785507   423.513515   9693.109058
3        -122.213344  0.144433   1835.443506   541.362922  12809.343648
4        -122.189139  0.134530   2291.124818   717.011186  13727.256030
5        -122.201242  0.122936   2442.706433   810.696482  13089.471580
6        -122.240728  0.108627   2280.176471   811.522085  14756.878676
7        -122.240711  0.117085   2335.263158   824.400640  15811.289474
8        -122.268769  0.067218   2265.384615  1083.994276   7355.923077
9        -122.311333  0.017328   2091.333333   552.024154   4387.833333
10       -122.202667  0.106237   2193.333333   478.783180   8686.333333
11       -122.363000       NaN   1420.000000          NaN   4960.000000
33       -122.331000       NaN   1330.000000          NaN   4700.000000


                   std
bedrooms
0         60292.876198
1         35664.464995
2         25795.371242
3         27249.179317
4         28511.479477
5         20848.065131
6         34100.083352
7         34819.366375
8          4734.568010
9          1267.205495
10         4345.760041
11                 NaN
33                 NaN

[13 rows x 36 columns]

Describe can be used on grouped dataframes as well.

In [23]:
group_df.describe()

         bathrooms                                                     \
             count      mean       std   min   25%   50%    75%   max
bedrooms
0             13.0  0.826923  1.067438  0.00  0.00  0.00  1.500  2.50
1            199.0  1.066583  0.363626  0.00  1.00  1.00  1.000  2.50
2           2760.0  1.401721  0.540169  0.50  1.00  1.00  1.750  3.50
3           9824.0  1.968394  0.629864  0.75  1.50  2.00  2.500  4.50
4           6882.0  2.436428  0.646521  0.50  2.00  2.50  2.750  5.75
5           1601.0  2.778576  0.835774  1.00  2.25  2.75  3.250  6.75
6            272.0  3.068015  1.065419  1.00  2.50  3.00  3.750  8.00
7             38.0  3.651316  1.385908  1.00  2.75  3.50  4.250  8.00
8             13.0  3.557692  1.011156  2.50  2.75  3.25  4.000  6.00
9              6.0  4.416667  1.655798  3.00  3.25  4.25  4.500  7.50
10             3.0  3.416667  1.664582  2.00  2.50  3.00  4.125  5.25
11             1.0  3.000000       NaN  3.00  3.00  3.00  3.000  3.00
33             1.0  1.750000       NaN  1.75  1.75  1.75  1.750  1.75

         condition             ...    yr_renovated         zipcode  \
             count      mean   ...             75%     max   count
bedrooms                       ...
0             13.0  2.846154   ...             0.0     0.0    13.0
1            199.0  3.266332   ...             0.0  2014.0   199.0
2           2760.0  3.377899   ...             0.0  2014.0  2760.0
3           9824.0  3.415513   ...             0.0  2015.0  9824.0
4           6882.0  3.406568   ...             0.0  2015.0  6882.0
5           1601.0  3.449094   ...             0.0  2015.0  1601.0
6            272.0  3.470588   ...             0.0  2015.0   272.0
7             38.0  3.447368   ...             0.0  2013.0    38.0
8             13.0  3.538462   ...             0.0     0.0    13.0
9              6.0  3.000000   ...             0.0  2010.0     6.0
10             3.0  3.666667   ...             0.0     0.0     3.0
11             1.0  3.000000   ...          1999.0  1999.0     1.0
33             1.0  5.000000   ...             0.0     0.0     1.0

                                                                        \
                  mean        std      min       25%      50%      75%
bedrooms
0         98066.692308  41.557961  98001.0  98038.00  98065.0  98102.0
1         98103.417085  49.630370  98001.0  98070.00  98116.0  98126.0
2         98105.953623  47.419698  98001.0  98070.00  98116.0  98133.0
3         98076.478217  53.724672  98001.0  98031.00  98059.0  98117.0
4         98069.749201  51.665516  98001.0  98030.00  98056.0  98112.0
5         98070.188007  53.601705  98001.0  98028.00  98056.0  98115.0
6         98079.463235  54.738548  98001.0  98030.75  98097.0  98118.0
7         98085.815789  53.339735  98004.0  98039.25  98104.0  98121.0
8         98081.846154  45.012676  98004.0  98055.00  98105.0  98112.0
9         98110.666667  16.378848  98102.0  98103.50  98105.0  98105.0
10        98038.333333  57.743687  98004.0  98005.00  98006.0  98055.5
11        98106.000000        NaN  98106.0  98106.00  98106.0  98106.0
33        98103.000000        NaN  98103.0  98103.00  98103.0  98103.0


              max
bedrooms
0         98133.0
1         98199.0
2         98199.0
3         98199.0
4         98199.0
5         98199.0
6         98199.0
7         98199.0
8         98133.0
9         98144.0
10        98105.0
11        98106.0
33        98103.0

[13 rows x 144 columns]

In [24]:
group_df['bedrooms'].count()[0]

13

idxmax returns the maximum column values for each group

In [25]:
group_df.idxmax()

,price,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
bedrooms,,,,,,,,,,,,,,,,,,
0,2.954400e+09,2.569500e+09,2954400190,1222029077,6.306400e+09,6306400140,6306400140,9543000205,2954400190,2954400190,6306400140,3918400017,6306400140,3918400017,1.453602e+09,7.849202e+09,2954400190,1222029077
1,7.240690e+08,4.083304e+09,2025079033,1222069089,2.767604e+09,2123039032,2123039032,2123039032,8835800480,2025079033,8122100355,3076500830,8122100355,7010701016,1.260393e+08,8.649401e+09,1720800305,1921069059
2,7.524900e+09,3.019300e+09,7524900003,3326079016,1.702901e+09,8096000060,8096000060,2009000370,1827200265,7524900003,7524900003,1250200495,3290800215,582000135,8.165100e+09,1.437500e+09,3425059076,2624089007
3,2.303900e+09,4.055700e+09,4379600030,2522029039,1.972202e+09,822039084,2524049179,1202000200,2303900100,7631800015,4379600030,9385200045,2202500255,4235400186,5.500200e+09,1.437500e+09,5700004525,3420069060
4,3.835500e+09,2.626069e+09,2524069078,1020069017,2.767602e+09,2025069065,2025069065,2487200875,7237501190,2524069078,624069108,1832100030,6821100195,2021201000,7.280300e+09,1.723099e+09,2524069078,225079036
5,9.808701e+09,1.924059e+09,9808700762,2623069031,3.271800e+09,1247600105,7922800400,2599001200,2470100110,6072800246,1924059029,9520900210,8712100320,5036300431,7.280300e+09,1.223089e+09,3303850390,8835770170
6,6.762700e+09,6.762700e+09,6762700020,3020079078,5.379804e+09,7558700030,7558700030,6190701146,6762700020,9208900037,6762700020,2402100575,6071800100,8941100095,2.260393e+08,7.852011e+09,715010130,3020079078
7,7.159200e+09,1.225069e+09,1225069038,1225069038,1.225069e+09,5486800070,1225069038,686400380,1225069038,1225069038,1225069038,4006000183,1683400165,2771604190,4.024101e+09,1.225069e+09,1225069038,1225069038
8,1.346300e+09,6.850001e+08,1346300150,1652500060,1.346300e+09,9126101740,1338600225,1338600225,1346300150,1346300150,1652500060,9126101740,9126101740,1873400020,1.873400e+09,7.418000e+09,1338600225,1652500060
9,8.823900e+09,4.240490e+08,8823900290,1997200215,1.997200e+09,1997200215,1997200215,1997200215,8823900290,424049043,1997200215,424049043,9822700190,424049043,1.997200e+09,9.822700e+09,8823900290,1997200215
10,6.273001e+08,6.273001e+08,627300145,5566100170,5.566100e+09,627300145,627300145,5566100170,627300145,5566100170,627300145,627300145,627300145,8812401450,8.812401e+09,6.273001e+08,627300145,5566100170
11,1.773101e+09,1.773101e+09,1773100755,1773100755,1.773101e+09,1773100755,1773100755,1773100755,1773100755,1773100755,1773100755,1773100755,1773100755,1773100755,1.773101e+09,1.773101e+09,1773100755,1773100755
33,2.402101e+09,2.402101e+09,2402100895,2402100895,2.402101e+09,2402100895,2402100895,2402100895,2402100895,2402100895,2402100895,2402100895,2402100895,2402100895,2.402101e+09,2.402101e+09,2402100895,2402100895

In [26]:
group_df.idxmin()

,price,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
bedrooms,,,,,,,,,,,,,,,,,,
0,9.543000e+09,6.306400e+09,3980300371,3918400017,6.896300e+09,6306400140,1453602309,3980300371,3980300371,3980300371,6306400140,9543000205,6306400140,9543000205,9.543000e+09,1.222029e+09,7849202190,3918400017
1,3.421079e+09,3.421079e+09,2856101479,688000017,7.920100e+09,7920100045,7920100045,913000340,3421079032,2856101479,7920100045,3364900156,7920100045,4031000520,2.420069e+09,3.023039e+09,6840700165,1702901618
2,4.000036e+07,3.971701e+09,3523029041,6371000026,5.631500e+09,5631500400,5631500400,1726059053,5279100625,3523029041,5631500400,9274202270,5631500400,8856004730,5.702381e+09,3.523029e+09,3822200036,2827100075
3,3.883800e+09,8.888000e+09,1437500015,1773101159,7.129301e+09,7129300520,7129300520,5694000710,6730700385,1437500015,7129300520,3626039325,7129300520,4014400292,9.413400e+09,3.522029e+09,2722059275,7899800863
4,7.224001e+09,2.991000e+09,4337000335,9828702895,2.487201e+09,2487200875,2487200875,9435300030,9435300030,3031200120,6865200140,7011200260,2487200875,7895500070,6.190790e+08,2.622029e+09,422000075,2827100070
5,7.129305e+09,3.812400e+09,3580900260,7129303045,7.231300e+09,1175000570,1175000570,5152600090,3320000810,1900600040,1175000570,1175000570,1175000570,1311000600,3.220079e+09,2.623029e+09,9421500130,9828702890
6,1.823049e+09,8.090009e+08,5132000140,6850700670,9.264902e+09,6300000550,6300000550,9187200095,7227800110,6746701090,2946001550,9551201585,9264902050,3353400840,3.020079e+09,1.068000e+09,1180002470,6746701090
7,2.887950e+09,3.812400e+09,2887950020,2856100381,4.024101e+09,5486800070,4024100951,5486800070,2856100381,7227802030,5451100490,9187200345,4024100951,5536100005,2.887950e+09,2.818600e+09,2862100366,3052700225
8,1.873400e+09,6.746701e+09,6746700615,9126101740,7.226500e+09,9126101740,9126101740,9126101740,7226500100,6746700615,685000115,8141200080,9126101740,685000115,7.418000e+09,2.769601e+09,3756900027,9126101740
9,4.240490e+08,2.902200e+09,8823901445,2902200015,2.902200e+09,1997200215,1997200215,1997200215,1997200215,8823901445,424049043,2902200015,1997200215,2902200015,4.240490e+08,1.997200e+09,424049043,2902200015
10,5.566100e+09,5.566100e+09,8812401450,8812401450,6.273001e+08,627300145,5566100170,627300145,5566100170,8812401450,5566100170,8812401450,627300145,627300145,5.566100e+09,8.812401e+09,8812401450,8812401450
11,1.773101e+09,1.773101e+09,1773100755,1773100755,1.773101e+09,1773100755,1773100755,1773100755,1773100755,1773100755,1773100755,1773100755,1773100755,1773100755,1.773101e+09,1.773101e+09,1773100755,1773100755
33,2.402101e+09,2.402101e+09,2402100895,2402100895,2.402101e+09,2402100895,2402100895,2402100895,2402100895,2402100895,2402100895,2402100895,2402100895,2402100895,2.402101e+09,2.402101e+09,2402100895,2402100895

# Stacking

Given two of more dataframe objects, it is common to require to join them together.

When two dataframes contain identical column structures, they can be vertically stacked using concat

In [27]:
df1 = df[:200]
df2 = df[201:401]

In [28]:
df1.head(3)
df1.shape

(200, 20)

In [29]:
df2.head(3)
df2.shape

(200, 20)

In [30]:
df3 = pd.concat([df1,df2])

In [31]:
df3.shape

(400, 20)

the same can be down for joining columns together

In [32]:
df4 = df1.iloc[:,:5]
df5 = df1.iloc[:,5:]

In [33]:
df4.head()

                       date     price  bedrooms  bathrooms  sqft_living
id
7129300520  20141013T000000  221900.0         3       1.00         1180
6414100192  20141209T000000  538000.0         3       2.25         2570
5631500400  20150225T000000  180000.0         2       1.00          770
2487200875  20141209T000000  604000.0         4       3.00         1960
1954400510  20150218T000000  510000.0         3       2.00         1680

In [34]:
df5.head()

,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,
7129300520,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

axis = 1 specifies that the concatenation is occuring on the columns rather than rows (default axis = 0, reffering to rows)

In [35]:
df6 = pd.concat([df4, df5], axis = 1)

In [36]:
df6.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

## Pivot Tables

Pivot tables allow for easy summaries of the explored data frame, allowing descriptive statistics to be group and displayed over different columns

In [37]:
df.pivot_table('price', index = 'bedrooms', columns = 'sqft_living')

sqft_living,290,370,380,384,390,410,420,430,440,460,...,8000,8010,8020,8670,9200,9640,9890,10040,12050,13540
bedrooms,,,,,,,,,,,,,,,,,,,,,
0,142000.0,NaN,NaN,265000.0,228000.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,276000.0,245000.0,NaN,245000.0,325000.0,254525.0,80000.0,NaN,247000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,290000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5350000.0,5110800.0,3300000.0,2888000.0,5570000.0,4668000.0,NaN,7062500.0,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6885000.0,NaN,7700000.0,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2280000.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Multiple columns and indexs can also be selected, and margins can add additional summary

In [42]:
df.pivot_table('price', index = 'bedrooms', columns = ['sqft_living', 'sqft_lot'], margins = all)

sqft_living       290       370       380       384       390            \
sqft_lot        20875      1801     15000    213444      2000      5900
bedrooms
0            142000.0       NaN       NaN  265000.0       NaN  228000.0
1                 NaN  276000.0  245000.0       NaN  245000.0       NaN
2                 NaN       NaN       NaN       NaN       NaN       NaN
3                 NaN       NaN       NaN       NaN       NaN       NaN
4                 NaN       NaN       NaN       NaN       NaN       NaN
5                 NaN       NaN       NaN       NaN       NaN       NaN
6                 NaN       NaN       NaN       NaN       NaN       NaN
7                 NaN       NaN       NaN       NaN       NaN       NaN
8                 NaN       NaN       NaN       NaN       NaN       NaN
9                 NaN       NaN       NaN       NaN       NaN       NaN
10                NaN       NaN       NaN       NaN       NaN       NaN
11                NaN       NaN       NaN       NaN       NaN       NaN
33                NaN       NaN       NaN       NaN       NaN       NaN
All          142000.0  276000.0  245000.0  265000.0  245000.0  228000.0

sqft_living       410       420                430      ...            8010  \
sqft_lot         8636      3298      6720     5050      ...           45517
bedrooms                                                ...
0                 NaN       NaN       NaN      NaN      ...             NaN
1            325000.0  229050.0  280000.0  80000.0      ...             NaN
2                 NaN       NaN       NaN      NaN      ...             NaN
3                 NaN       NaN       NaN      NaN      ...             NaN
4                 NaN       NaN       NaN      NaN      ...             NaN
5                 NaN       NaN       NaN      NaN      ...       5110800.0
6                 NaN       NaN       NaN      NaN      ...             NaN
7                 NaN       NaN       NaN      NaN      ...             NaN
8                 NaN       NaN       NaN      NaN      ...             NaN
9                 NaN       NaN       NaN      NaN      ...             NaN
10                NaN       NaN       NaN      NaN      ...             NaN
11                NaN       NaN       NaN      NaN      ...             NaN
33                NaN       NaN       NaN      NaN      ...             NaN
All          325000.0  229050.0  280000.0  80000.0      ...       5110800.0

sqft_living       8020       8670       9200       9640       9890      10040  \
sqft_lot         21738      64033      35069      13068      31374      37325
bedrooms
0                  NaN        NaN        NaN        NaN        NaN        NaN
1                  NaN        NaN        NaN        NaN        NaN        NaN
2                  NaN        NaN        NaN        NaN        NaN        NaN
3                  NaN        NaN        NaN        NaN        NaN        NaN
4                  NaN        NaN        NaN        NaN        NaN        NaN
5            3300000.0  2888000.0  5570000.0  4668000.0        NaN  7062500.0
6                  NaN        NaN        NaN        NaN  6885000.0        NaN
7                  NaN        NaN        NaN        NaN        NaN        NaN
8                  NaN        NaN        NaN        NaN        NaN        NaN
9                  NaN        NaN        NaN        NaN        NaN        NaN
10                 NaN        NaN        NaN        NaN        NaN        NaN
11                 NaN        NaN        NaN        NaN        NaN        NaN
33                 NaN        NaN        NaN        NaN        NaN        NaN
All          3300000.0  2888000.0  5570000.0  4668000.0  6885000.0  7062500.0

sqft_living      12050      13540           All
sqft_lot         27600     307752
bedrooms
0                  NaN        NaN  4.095038e+05
1                  NaN        NaN  3.176429e+05
2                  NaN        NaN  4.013727e+05
3                  NaN        NaN  4.662321e+05
4                  NaN        NaN  6.354195e+05
5                  NaN        NaN  7.865998e+05
6            7700000.0        NaN  8.255206e+05
7                  NaN  2280000.0  9.511847e+05
8                  NaN        NaN  1.105077e+06
9                  NaN        NaN  8.939998e+05
10                 NaN        NaN  8.193333e+05
11                 NaN        NaN  5.200000e+05
33                 NaN        NaN  6.400000e+05
All          7700000.0  2280000.0  5.400881e+05

[14 rows x 20500 columns]

In [39]:
df.pivot_table('price', index = ['bedrooms','view'], columns = ['sqft_living', 'sqft_lot'])

sqft_living       290       370       380       384       390              \
sqft_lot         20875     1801      15000     213444    2000      5900
bedrooms view
0        0     142000.0       NaN       NaN  265000.0       NaN  228000.0
         2          NaN       NaN       NaN       NaN       NaN       NaN
1        0          NaN  276000.0  245000.0       NaN  245000.0       NaN
         1          NaN       NaN       NaN       NaN       NaN       NaN
         2          NaN       NaN       NaN       NaN       NaN       NaN
         3          NaN       NaN       NaN       NaN       NaN       NaN
         4          NaN       NaN       NaN       NaN       NaN       NaN
2        0          NaN       NaN       NaN       NaN       NaN       NaN
         1          NaN       NaN       NaN       NaN       NaN       NaN
         2          NaN       NaN       NaN       NaN       NaN       NaN
         3          NaN       NaN       NaN       NaN       NaN       NaN
         4          NaN       NaN       NaN       NaN       NaN       NaN
3        0          NaN       NaN       NaN       NaN       NaN       NaN
         1          NaN       NaN       NaN       NaN       NaN       NaN
         2          NaN       NaN       NaN       NaN       NaN       NaN
         3          NaN       NaN       NaN       NaN       NaN       NaN
         4          NaN       NaN       NaN       NaN       NaN       NaN
4        0          NaN       NaN       NaN       NaN       NaN       NaN
         1          NaN       NaN       NaN       NaN       NaN       NaN
         2          NaN       NaN       NaN       NaN       NaN       NaN
         3          NaN       NaN       NaN       NaN       NaN       NaN
         4          NaN       NaN       NaN       NaN       NaN       NaN
5        0          NaN       NaN       NaN       NaN       NaN       NaN
         1          NaN       NaN       NaN       NaN       NaN       NaN
         2          NaN       NaN       NaN       NaN       NaN       NaN
         3          NaN       NaN       NaN       NaN       NaN       NaN
         4          NaN       NaN       NaN       NaN       NaN       NaN
6        0          NaN       NaN       NaN       NaN       NaN       NaN
         1          NaN       NaN       NaN       NaN       NaN       NaN
         2          NaN       NaN       NaN       NaN       NaN       NaN
         3          NaN       NaN       NaN       NaN       NaN       NaN
         4          NaN       NaN       NaN       NaN       NaN       NaN
7        0          NaN       NaN       NaN       NaN       NaN       NaN
         1          NaN       NaN       NaN       NaN       NaN       NaN
         2          NaN       NaN       NaN       NaN       NaN       NaN
         4          NaN       NaN       NaN       NaN       NaN       NaN
8        0          NaN       NaN       NaN       NaN       NaN       NaN
         3          NaN       NaN       NaN       NaN       NaN       NaN
9        0          NaN       NaN       NaN       NaN       NaN       NaN
10       0          NaN       NaN       NaN       NaN       NaN       NaN
         2          NaN       NaN       NaN       NaN       NaN       NaN
11       0          NaN       NaN       NaN       NaN       NaN       NaN
33       0          NaN       NaN       NaN       NaN       NaN       NaN

sqft_living       410       420                430      ...          8000   \
sqft_lot         8636      3298      6720     5050      ...         23985
bedrooms view                                           ...
0        0          NaN       NaN       NaN      NaN    ...            NaN
         2          NaN       NaN       NaN      NaN    ...            NaN
1        0     325000.0  229050.0  280000.0  80000.0    ...            NaN
         1          NaN       NaN       NaN      NaN    ...            NaN
         2          NaN       NaN       NaN      NaN    ...            NaN
         3          NaN       NaN       NaN      NaN    ...            NaN
         4          NaN       NaN       NaN      NaN    ...            NaN
2        0          NaN       NaN       NaN      NaN    ...            NaN
         1          NaN       NaN       NaN      NaN    ...            NaN
         2          NaN       NaN       NaN      NaN    ...            NaN
         3          NaN       NaN       NaN      NaN    ...            NaN
         4          NaN       NaN       NaN      NaN    ...            NaN
3        0          NaN       NaN       NaN      NaN    ...            NaN
         1          NaN       NaN       NaN      NaN    ...            NaN
         2          NaN       NaN       NaN      NaN    ...            NaN
         3          NaN       NaN       NaN      NaN    ...            NaN
         4          NaN       NaN       NaN      NaN    ...            NaN
4        0          NaN       NaN       NaN      NaN    ...            NaN
         1          NaN       NaN       NaN      NaN    ...            NaN
         2          NaN       NaN       NaN      NaN    ...            NaN
         3          NaN       NaN       NaN      NaN    ...            NaN
         4          NaN       NaN       NaN      NaN    ...            NaN
5        0          NaN       NaN       NaN      NaN    ...            NaN
         1          NaN       NaN       NaN      NaN    ...            NaN
         2          NaN       NaN       NaN      NaN    ...            NaN
         3          NaN       NaN       NaN      NaN    ...            NaN
         4          NaN       NaN       NaN      NaN    ...      5350000.0
6        0          NaN       NaN       NaN      NaN    ...            NaN
         1          NaN       NaN       NaN      NaN    ...            NaN
         2          NaN       NaN       NaN      NaN    ...            NaN
         3          NaN       NaN       NaN      NaN    ...            NaN
         4          NaN       NaN       NaN      NaN    ...            NaN
7        0          NaN       NaN       NaN      NaN    ...            NaN
         1          NaN       NaN       NaN      NaN    ...            NaN
         2          NaN       NaN       NaN      NaN    ...            NaN
         4          NaN       NaN       NaN      NaN    ...            NaN
8        0          NaN       NaN       NaN      NaN    ...            NaN
         3          NaN       NaN       NaN      NaN    ...            NaN
9        0          NaN       NaN       NaN      NaN    ...            NaN
10       0          NaN       NaN       NaN      NaN    ...            NaN
         2          NaN       NaN       NaN      NaN    ...            NaN
11       0          NaN       NaN       NaN      NaN    ...            NaN
33       0          NaN       NaN       NaN      NaN    ...            NaN

sqft_living        8010       8020       8670       9200       9640   \
sqft_lot          45517      21738      64033      35069      13068
bedrooms view
0        0           NaN        NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN        NaN
1        0           NaN        NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN        NaN
2        0           NaN        NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN        NaN
3        0           NaN        NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN        NaN
4        0           NaN        NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN        NaN
5        0           NaN  3300000.0        NaN  5570000.0        NaN
         1           NaN        NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN        NaN
         4     5110800.0        NaN  2888000.0        NaN  4668000.0
6        0           NaN        NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN        NaN
7        0           NaN        NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN        NaN
8        0           NaN        NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN        NaN
9        0           NaN        NaN        NaN        NaN        NaN
10       0           NaN        NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN        NaN
11       0           NaN        NaN        NaN        NaN        NaN
33       0           NaN        NaN        NaN        NaN        NaN

sqft_living        9890       10040      12050      13540
sqft_lot          31374      37325      27600      307752
bedrooms view
0        0           NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN
1        0           NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN
2        0           NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN
3        0           NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN
4        0           NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN
5        0           NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN
         2           NaN  7062500.0        NaN        NaN
         3           NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN        NaN
6        0           NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN
         3           NaN        NaN  7700000.0        NaN
         4     6885000.0        NaN        NaN        NaN
7        0           NaN        NaN        NaN        NaN
         1           NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN
         4           NaN        NaN        NaN  2280000.0
8        0           NaN        NaN        NaN        NaN
         3           NaN        NaN        NaN        NaN
9        0           NaN        NaN        NaN        NaN
10       0           NaN        NaN        NaN        NaN
         2           NaN        NaN        NaN        NaN
11       0           NaN        NaN        NaN        NaN
33       0           NaN        NaN        NaN        NaN

[43 rows x 20499 columns]

The default aggregate function returned by the pivot table is the mean, however additional aggregate functions such as maximum, median, standard deviation etc can be specified

In [43]:
df.pivot_table('price', index = ['bedrooms','view'], columns = ['grade'], aggfunc = ['mean','std'])

                   mean                                               \
grade                1              3              4              5
bedrooms view
0        0     142000.0            NaN  246500.000000            NaN
         2          NaN            NaN            NaN            NaN
1        0          NaN  205666.666667  204913.636364  245943.235294
         1          NaN            NaN            NaN            NaN
         2          NaN            NaN  355000.000000  192500.000000
         3          NaN            NaN            NaN            NaN
         4          NaN            NaN            NaN  327450.000000
2        0          NaN            NaN  188166.666667  234588.514019
         1          NaN            NaN  326000.000000  375000.000000
         2          NaN            NaN            NaN  443333.333333
         3          NaN            NaN            NaN  290000.000000
         4          NaN            NaN            NaN  686500.000000
3        0          NaN            NaN  205000.000000  233491.550000
         1          NaN            NaN            NaN  295000.000000
         2          NaN            NaN            NaN  249000.000000
         3          NaN            NaN            NaN            NaN
         4          NaN            NaN            NaN            NaN
4        0          NaN            NaN            NaN  258518.350000
         1          NaN            NaN            NaN            NaN
         2          NaN            NaN            NaN  255500.000000
         3          NaN            NaN            NaN            NaN
         4          NaN            NaN            NaN            NaN
5        0          NaN            NaN            NaN  328000.000000
         1          NaN            NaN            NaN            NaN
         2          NaN            NaN            NaN            NaN
         3          NaN            NaN            NaN            NaN
         4          NaN            NaN            NaN            NaN
6        0          NaN            NaN            NaN  281666.666667
         1          NaN            NaN            NaN            NaN
         2          NaN            NaN            NaN            NaN
         3          NaN            NaN            NaN            NaN
         4          NaN            NaN            NaN            NaN
7        0          NaN            NaN            NaN            NaN
         1          NaN            NaN            NaN            NaN
         2          NaN            NaN            NaN            NaN
         4          NaN            NaN            NaN            NaN
8        0          NaN            NaN            NaN            NaN
         3          NaN            NaN            NaN            NaN
9        0          NaN            NaN            NaN            NaN
10       0          NaN            NaN            NaN            NaN
         2          NaN            NaN            NaN            NaN
11       0          NaN            NaN            NaN            NaN
33       0          NaN            NaN            NaN            NaN

                                                                        \
grade                     6             7             8             9
bedrooms view
0        0               NaN  2.445900e+05  3.474750e+05           NaN
         2               NaN  1.095000e+06  3.800000e+05           NaN
1        0     302056.273973  3.726500e+05  2.897222e+05  5.332500e+05
         1               NaN  2.635000e+05           NaN           NaN
         2     199750.000000           NaN  5.799667e+05           NaN
         3               NaN  5.882500e+05  6.112060e+05           NaN
         4     382333.333333           NaN  1.247000e+06           NaN
2        0     293266.649168  4.034788e+05  4.735772e+05  6.305811e+05
         1     376864.090909  5.113786e+05  7.104286e+05           NaN
         2     414409.090909  4.886260e+05  6.221092e+05  6.036667e+05
         3     440600.000000  5.124433e+05  7.286250e+05  9.441933e+05
         4     592518.400000  7.105500e+05  9.235000e+05  1.162429e+06
3        0     287840.423402  3.765632e+05  4.940498e+05  6.782945e+05
         1     310000.000000  5.253204e+05  7.429267e+05  8.443933e+05
         2     433646.666667  4.895339e+05  6.751727e+05  8.275981e+05
         3     357998.333333  4.424162e+05  6.877267e+05  8.699503e+05
         4     711000.000000  7.813636e+05  1.018462e+06  1.118292e+06
4        0     321843.892857  4.197204e+05  5.409399e+05  7.414106e+05
         1     405000.000000  5.918744e+05  7.240726e+05  9.566554e+05
         2     353245.000000  5.041046e+05  6.738949e+05  9.032711e+05
         3     456666.666667  5.289800e+05  7.669849e+05  9.782817e+05
         4     685000.000000  9.838125e+05  1.051614e+06  1.131993e+06
5        0     357596.250000  4.538629e+05  5.917749e+05  8.616275e+05
         1               NaN  6.432500e+05  6.774583e+05  1.178833e+06
         2     565000.000000  4.676366e+05  7.115025e+05  9.329058e+05
         3               NaN  5.567071e+05  8.586890e+05  1.239810e+06
         4               NaN  4.560000e+05  1.317162e+06  1.233139e+06
6        0     430355.714286  4.917621e+05  6.339686e+05  9.336527e+05
         1               NaN           NaN  5.895000e+05  9.590000e+05
         2               NaN  5.153573e+05  8.013250e+05  8.878000e+05
         3               NaN           NaN  9.173333e+05  1.112750e+06
         4               NaN  9.750000e+05  1.479400e+06  1.026375e+06
7        0     580000.000000  4.758000e+05  6.224217e+05  9.342667e+05
         1               NaN           NaN  6.820000e+05           NaN
         2               NaN  3.500000e+05           NaN           NaN
         4               NaN           NaN           NaN  1.185000e+06
8        0               NaN  5.793333e+05  9.925000e+05  1.650000e+06
         3               NaN           NaN           NaN           NaN
9        0               NaN  6.709998e+05  1.280000e+06           NaN
10       0               NaN  6.550000e+05           NaN           NaN
         2               NaN           NaN           NaN  1.148000e+06
11       0               NaN  5.200000e+05           NaN           NaN
33       0               NaN  6.400000e+05           NaN           NaN

                                               ...                 std  \
grade                    10            11      ...                  4
bedrooms view                                  ...
0        0              NaN           NaN      ...        26162.950904
         2              NaN           NaN      ...                 NaN
1        0     3.160000e+05           NaN      ...        93511.133270
         1              NaN           NaN      ...                 NaN
         2              NaN           NaN      ...                 NaN
         3              NaN           NaN      ...                 NaN
         4              NaN           NaN      ...                 NaN
2        0     7.773916e+05  1.145785e+06      ...        85842.173714
         1              NaN           NaN      ...       154149.278299
         2     1.198333e+06           NaN      ...                 NaN
         3     1.197250e+06           NaN      ...                 NaN
         4     1.306650e+06  3.278000e+06      ...                 NaN
3        0     8.641756e+05  1.120291e+06      ...                 NaN
         1     9.657143e+05  1.153000e+06      ...                 NaN
         2     1.028427e+06  1.548889e+06      ...                 NaN
         3     1.161796e+06  1.559583e+06      ...                 NaN
         4     1.759375e+06  2.736250e+06      ...                 NaN
4        0     9.666570e+05  1.273925e+06      ...                 NaN
         1     1.289072e+06  1.703360e+06      ...                 NaN
         2     1.182412e+06  1.564294e+06      ...                 NaN
         3     1.447702e+06  1.601482e+06      ...                 NaN
         4     1.773667e+06  1.857677e+06      ...                 NaN
5        0     1.171118e+06  1.448458e+06      ...                 NaN
         1     1.780000e+06  2.442800e+06      ...                 NaN
         2     1.100794e+06  1.985694e+06      ...                 NaN
         3     1.491038e+06  1.813500e+06      ...                 NaN
         4     2.249395e+06  1.896286e+06      ...                 NaN
6        0     1.323584e+06  1.348143e+06      ...                 NaN
         1              NaN           NaN      ...                 NaN
         2     1.161667e+06  1.871250e+06      ...                 NaN
         3     1.470000e+06  1.600000e+06      ...                 NaN
         4     1.510000e+06  3.650000e+06      ...                 NaN
7        0     1.640200e+06           NaN      ...                 NaN
         1              NaN  1.950000e+06      ...                 NaN
         2              NaN  2.150000e+06      ...                 NaN
         4              NaN           NaN      ...                 NaN
8        0              NaN           NaN      ...                 NaN
         3     1.970000e+06           NaN      ...                 NaN
9        0              NaN  1.400000e+06      ...                 NaN
10       0              NaN           NaN      ...                 NaN
         2              NaN           NaN      ...                 NaN
11       0              NaN           NaN      ...                 NaN
33       0              NaN           NaN      ...                 NaN

                                                                           \
grade                     5              6              7              8
bedrooms view
0        0               NaN            NaN   68252.586032   10641.957057
         2               NaN            NaN            NaN            NaN
1        0     116040.680085  111730.946892  124626.826370  115570.084557
         1               NaN            NaN   12020.815280            NaN
         2               NaN   42072.853481            NaN  151544.723872
         3               NaN            NaN   75306.872196            NaN
         4      60033.365723  166572.306622            NaN            NaN
2        0     115204.947439  110708.436671  137257.527572  156996.671868
         1               NaN  110316.339379  166603.585324  158973.642619
         2     305791.323182  192686.189262  163189.391876  148803.983021
         3               NaN  190379.358125  154715.251026  200334.053407
         4      40305.086528  165051.518299  172411.080141  353374.750493
3        0      92658.278505  116728.207032  143386.761982  165059.631321
         1               NaN            NaN  211264.451857  323702.263171
         2               NaN  182385.060152  167502.659726  253663.861842
         3               NaN   21366.609854  137486.195296  232032.925409
         4               NaN  436429.833994  408686.009726  559694.028463
4        0      95029.011070  122590.836639  153569.546253  201242.797869
         1               NaN   93674.969976  255040.367579  312213.107100
         2               NaN  129761.165416  157499.683255  208463.767832
         3               NaN  210792.156717  213176.040774  271813.136036
         4               NaN            NaN  488334.482670  442275.553296
5        0      88360.058850  120097.330927  172289.338993  214367.337528
         1               NaN            NaN  291814.295971  189177.092764
         2               NaN            NaN  118843.239096  265133.204376
         3               NaN            NaN  142466.430047  312309.541052
         4               NaN            NaN            NaN  632888.499847
6        0      45368.858629  234515.480787  183457.462726  225859.942793
         1               NaN            NaN            NaN  267993.470070
         2               NaN            NaN  138462.327738  354219.455282
         3               NaN            NaN            NaN  475338.125268
         4               NaN            NaN            NaN  594818.224334
7        0               NaN            NaN  149241.638515  156965.471058
         1               NaN            NaN            NaN  200818.325857
         2               NaN            NaN            NaN            NaN
         4               NaN            NaN            NaN            NaN
8        0               NaN            NaN  188071.972039  799432.090091
         3               NaN            NaN            NaN            NaN
9        0               NaN            NaN  203217.569779            NaN
10       0               NaN            NaN    7071.067812            NaN
         2               NaN            NaN            NaN            NaN
11       0               NaN            NaN            NaN            NaN
33       0               NaN            NaN            NaN            NaN

                                                                         \
grade                     9              10            11            12
bedrooms view
0        0               NaN            NaN           NaN           NaN
         2               NaN            NaN           NaN           NaN
1        0      23688.077170            NaN           NaN           NaN
         1               NaN            NaN           NaN           NaN
         2               NaN            NaN           NaN           NaN
         3               NaN            NaN           NaN           NaN
         4               NaN            NaN           NaN           NaN
2        0     234485.202163  201033.979252  1.255610e+05           NaN
         1               NaN            NaN           NaN           NaN
         2      55338.353186  441597.478858           NaN           NaN
         3     435234.668043  346835.876172           NaN           NaN
         4     229908.573961  219395.130605           NaN           NaN
3        0     243927.972985  295598.314721  3.491540e+05  6.084253e+05
         1     306942.974247  301298.143752           NaN           NaN
         2     354511.306654  328681.878747  4.443080e+05  1.995754e+05
         3     388020.987409  359166.201688  5.752065e+05           NaN
         4     462462.046251  722025.867446  4.627538e+05  7.555889e+05
4        0     276308.979869  382604.924088  5.027454e+05  8.416810e+05
         1     271766.429310  500569.053288  6.809370e+05           NaN
         2     395055.639292  542466.826665  5.633043e+05  7.844447e+05
         3     383629.072273  603104.209295  5.541253e+05  3.892889e+05
         4     481502.840911  742888.584699  8.235038e+05  5.726739e+05
5        0     316904.225250  449446.412350  6.639181e+05  9.297752e+05
         1     503620.765060  477676.668888  6.550662e+05  6.363961e+05
         2     381889.735151  300291.867651  1.488718e+06           NaN
         3     527789.978973  374117.054368  5.737275e+05  8.697413e+04
         4     597350.126483  810925.146720  9.946934e+05  1.675609e+06
6        0     210445.938240  376183.590707  3.767879e+05           NaN
         1               NaN            NaN           NaN           NaN
         2     281006.583553  654681.856579  7.310082e+05           NaN
         3     729236.523701  728640.286195           NaN           NaN
         4     221508.229719  445841.900229           NaN  1.555635e+06
7        0      73867.539104  905709.776915           NaN           NaN
         1               NaN            NaN           NaN           NaN
         2               NaN            NaN  1.227803e+06           NaN
         4               NaN            NaN           NaN           NaN
8        0               NaN            NaN           NaN           NaN
         3               NaN            NaN           NaN           NaN
9        0               NaN            NaN           NaN           NaN
10       0               NaN            NaN           NaN           NaN
         2               NaN            NaN           NaN           NaN
11       0               NaN            NaN           NaN           NaN
33       0               NaN            NaN           NaN           NaN


grade                    13
bedrooms view
0        0              NaN
         2              NaN
1        0              NaN
         1              NaN
         2              NaN
         3              NaN
         4              NaN
2        0              NaN
         1              NaN
         2              NaN
         3              NaN
         4              NaN
3        0              NaN
         1              NaN
         2              NaN
         3              NaN
         4              NaN
4        0     3.959798e+05
         1              NaN
         2              NaN
         3              NaN
         4              NaN
5        0     2.185667e+06
         1              NaN
         2     9.793429e+05
         3              NaN
         4              NaN
6        0              NaN
         1              NaN
         2              NaN
         3              NaN
         4              NaN
7        0              NaN
         1              NaN
         2              NaN
         4              NaN
8        0              NaN
         3              NaN
9        0              NaN
10       0              NaN
         2              NaN
11       0              NaN
33       0              NaN

[43 rows x 23 columns]